//! Internal capability tokens for zero-trust inter-service boundaries.
//!
//! Phase 3.3 of the hardening roadmap. Every internal service call within
//! the ZP process requires an `InternalCapabilityToken` with the specific
//! action being authorized. Tokens are:
//!
//! - **Short-lived**: expire after 60 seconds.
//! - **Scoped**: bound to exactly one operation.
//! - **Signed**: carry an HMAC-SHA256 over the token fields.
//! - **Single-use**: consumed on first verification.
//!
//! This prevents SSRF exploitation: even if an attacker can make the server
//! call itself, the internal call lacks a valid capability token.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::sync::Mutex;

/// A short-lived, scoped token for authorizing internal service calls.
///
/// Generated by the pipeline orchestrator after policy evaluation, scoped
/// to exactly one operation, and verified at the service boundary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InternalCapabilityToken {
    /// Unique token identifier.
    pub token_id: String,

    /// What operation this token authorizes.
    pub scope: InternalScope,

    /// Who requested this operation (actor ID from the pipeline context).
    pub requestor: String,

    /// When this token was issued.
    pub issued_at: DateTime<Utc>,

    /// When this token expires (issued_at + 60 seconds).
    pub expires_at: DateTime<Utc>,

    /// HMAC-SHA256 over the canonical token fields, using the server's
    /// internal signing key. Prevents forgery.
    pub signature: String,
}

/// The operation that an internal capability token authorizes.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InternalScope {
    /// Execute code in the execution engine.
    Execute {
        /// The runtime allowed (e.g., "python", "node").
        runtime: String,
    },

    /// Proxy a request to an LLM provider.
    LlmProxy {
        /// The provider being proxied to.
        provider: String,
    },

    /// Append an entry to the audit trail.
    AuditAppend,

    /// Read from the audit trail.
    AuditRead,

    /// Issue or verify a receipt.
    ReceiptOp,

    /// Read or write credentials from the vault.
    VaultAccess {
        /// Whether write access is needed.
        write: bool,
    },

    /// Anchor a chain head to an external DLT.
    AnchorOp,

    /// Read or write observations (Phase 4).
    ObservationOp,
}

impl std::fmt::Display for InternalScope {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            InternalScope::Execute { runtime } => write!(f, "execute:{}", runtime),
            InternalScope::LlmProxy { provider } => write!(f, "llm_proxy:{}", provider),
            InternalScope::AuditAppend => write!(f, "audit:append"),
            InternalScope::AuditRead => write!(f, "audit:read"),
            InternalScope::ReceiptOp => write!(f, "receipt:op"),
            InternalScope::VaultAccess { write } => {
                write!(f, "vault:{}", if *write { "write" } else { "read" })
            }
            InternalScope::AnchorOp => write!(f, "anchor:op"),
            InternalScope::ObservationOp => write!(f, "observation:op"),
        }
    }
}

/// Default token lifetime: 60 seconds.
const TOKEN_LIFETIME_SECS: i64 = 60;

/// Issuer and verifier for internal capability tokens.
///
/// Holds the HMAC signing key and a set of consumed token IDs to enforce
/// single-use semantics.
pub struct InternalTokenAuthority {
    /// HMAC-SHA256 key for signing/verifying tokens.
    signing_key: [u8; 32],

    /// Set of token IDs that have been consumed (verified).
    /// Tokens are purged from this set when they would have expired anyway.
    consumed: Mutex<HashSet<String>>,
}

/// Errors from token operations.
#[derive(Debug, thiserror::Error)]
pub enum TokenError {
    #[error("Token has expired")]
    Expired,

    #[error("Token signature is invalid")]
    InvalidSignature,

    #[error("Token has already been consumed")]
    AlreadyConsumed,

    #[error("Token scope does not match the requested operation")]
    ScopeMismatch,
}

impl InternalTokenAuthority {
    /// Create a new authority with a random signing key.
    pub fn new() -> Self {
        let mut key = [0u8; 32];
        // Use blake3 hash of current time + random bytes as key material.
        // In production, this would use a proper CSPRNG.
        let seed = format!("{}-{}", Utc::now().timestamp_nanos_opt().unwrap_or(0), std::process::id());
        let hash = blake3::hash(seed.as_bytes());
        key.copy_from_slice(hash.as_bytes());

        Self {
            signing_key: key,
            consumed: Mutex::new(HashSet::new()),
        }
    }

    /// Create an authority with a specific key (for testing).
    pub fn with_key(key: [u8; 32]) -> Self {
        Self {
            signing_key: key,
            consumed: Mutex::new(HashSet::new()),
        }
    }

    /// Issue a new capability token for the given scope and requestor.
    pub fn issue(&self, scope: InternalScope, requestor: &str) -> InternalCapabilityToken {
        let token_id = format!("ict-{}", uuid::Uuid::now_v7());
        let issued_at = Utc::now();
        let expires_at = issued_at + Duration::seconds(TOKEN_LIFETIME_SECS);

        let signature = self.compute_signature(&token_id, &scope, requestor, &issued_at, &expires_at);

        InternalCapabilityToken {
            token_id,
            scope,
            requestor: requestor.to_string(),
            issued_at,
            expires_at,
            signature,
        }
    }

    /// Verify and consume a token. Returns Ok(()) if the token is valid,
    /// has not expired, has not been consumed, and matches the expected scope.
    pub fn verify(
        &self,
        token: &InternalCapabilityToken,
        expected_scope: &InternalScope,
    ) -> Result<(), TokenError> {
        // Check expiry
        if Utc::now() > token.expires_at {
            return Err(TokenError::Expired);
        }

        // Check scope
        if &token.scope != expected_scope {
            return Err(TokenError::ScopeMismatch);
        }

        // Check signature
        let expected_sig = self.compute_signature(
            &token.token_id,
            &token.scope,
            &token.requestor,
            &token.issued_at,
            &token.expires_at,
        );
        if token.signature != expected_sig {
            return Err(TokenError::InvalidSignature);
        }

        // Check single-use
        let mut consumed = self.consumed.lock().unwrap();

        // Garbage-collect expired tokens while we have the lock
        // (simple approach: we don't track expiry per token, just clear periodically)
        if consumed.len() > 10_000 {
            consumed.clear();
        }

        if consumed.contains(&token.token_id) {
            return Err(TokenError::AlreadyConsumed);
        }

        consumed.insert(token.token_id.clone());
        Ok(())
    }

    /// Compute HMAC-SHA256 over the canonical token fields.
    fn compute_signature(
        &self,
        token_id: &str,
        scope: &InternalScope,
        requestor: &str,
        issued_at: &DateTime<Utc>,
        expires_at: &DateTime<Utc>,
    ) -> String {
        // Use blake3 keyed hash as our MAC (simpler than pulling in hmac crate,
        // and blake3's keyed mode is a proper PRF).
        let canonical = format!(
            "{}:{}:{}:{}:{}",
            token_id,
            scope,
            requestor,
            issued_at.timestamp(),
            expires_at.timestamp()
        );
        blake3::keyed_hash(&self.signing_key, canonical.as_bytes())
            .to_hex()
            .to_string()
    }
}

impl Default for InternalTokenAuthority {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_issue_and_verify() {
        let authority = InternalTokenAuthority::with_key([42u8; 32]);
        let scope = InternalScope::Execute {
            runtime: "python".to_string(),
        };
        let token = authority.issue(scope.clone(), "pipeline-orchestrator");

        assert!(token.token_id.starts_with("ict-"));
        assert!(token.expires_at > token.issued_at);

        // Verify succeeds
        authority.verify(&token, &scope).unwrap();
    }

    #[test]
    fn test_single_use() {
        let authority = InternalTokenAuthority::with_key([42u8; 32]);
        let scope = InternalScope::AuditAppend;
        let token = authority.issue(scope.clone(), "pipeline");

        // First verification succeeds
        authority.verify(&token, &scope).unwrap();

        // Second verification fails (already consumed)
        let err = authority.verify(&token, &scope).unwrap_err();
        assert!(matches!(err, TokenError::AlreadyConsumed));
    }

    #[test]
    fn test_scope_mismatch() {
        let authority = InternalTokenAuthority::with_key([42u8; 32]);
        let scope = InternalScope::AuditAppend;
        let token = authority.issue(scope, "pipeline");

        // Wrong scope
        let err = authority
            .verify(&token, &InternalScope::AuditRead)
            .unwrap_err();
        assert!(matches!(err, TokenError::ScopeMismatch));
    }

    #[test]
    fn test_invalid_signature() {
        let authority = InternalTokenAuthority::with_key([42u8; 32]);
        let scope = InternalScope::AuditAppend;
        let mut token = authority.issue(scope.clone(), "pipeline");

        // Tamper with signature
        token.signature = "tampered".to_string();

        let err = authority.verify(&token, &scope).unwrap_err();
        assert!(matches!(err, TokenError::InvalidSignature));
    }

    #[test]
    fn test_expired_token() {
        let authority = InternalTokenAuthority::with_key([42u8; 32]);
        let scope = InternalScope::AuditAppend;
        let mut token = authority.issue(scope.clone(), "pipeline");

        // Force expiry into the past
        token.expires_at = Utc::now() - Duration::seconds(1);

        let err = authority.verify(&token, &scope).unwrap_err();
        assert!(matches!(err, TokenError::Expired));
    }
}
