//! `zp init` — bootstrap a new ZeroPoint environment.
//!
//! Generates the operator keypair, seals the constitutional bedrock,
//! writes the genesis record and zeropoint.toml. This is the first
//! command a developer runs.

use std::path::PathBuf;

use chrono::Utc;
use zp_keys::hierarchy::{GenesisKey, OperatorKey};
use zp_keys::keyring::Keyring;

use crate::commands::resolve_zp_home;

/// Configuration for `zp init`.
pub struct InitConfig {
    /// Operator name / subject for the certificate.
    pub operator_name: String,
    /// Directory to initialize in (defaults to current dir).
    pub project_dir: PathBuf,
    /// Whether to store the genesis secret key (default: true for dev).
    pub store_genesis_secret: bool,
}

/// Run the init command.
pub fn run(config: &InitConfig) -> i32 {
    let zp_dir = config.project_dir.join(".zeropoint");
    let toml_path = config.project_dir.join("zeropoint.toml");

    // The keyring always lives at ~/.zeropoint/keys/ (home directory),
    // consistent with `zp keys`, `zp secure`, `zp guard`, and `zp policy`.
    // The project-local .zeropoint/ holds config, policies, and data only.

    // ── Guard: don't re-init ────────────────────────────────────
    // Check the canonical home keyring, not the project-local dir
    let home_zp = resolve_zp_home();
    if home_zp.join("keys").join("genesis.json").exists() {
        eprintln!();
        eprintln!("  ZeroPoint is already initialized.");
        eprintln!("  Keyring: {}", home_zp.join("keys").display());
        eprintln!();
        eprintln!("  Remove ~/.zeropoint/ to re-initialize (this destroys all keys).");
        eprintln!();
        return 1;
    }

    // ── Banner ──────────────────────────────────────────────────
    eprintln!();
    eprintln!("  \x1b[1mZeroPoint Genesis\x1b[0m");
    eprintln!("  \x1b[2m─────────────────\x1b[0m");

    // ── Step 1: Generate keypair ────────────────────────────────
    eprint!("  Generating operator keypair...        ");
    let genesis = GenesisKey::generate(&config.operator_name);
    let operator = OperatorKey::generate(&config.operator_name, &genesis, None);
    eprintln!("\x1b[32m✓\x1b[0m Ed25519");

    // ── Step 2: Seal constitutional bedrock ─────────────────────
    eprint!("  Sealing constitutional bedrock...     ");
    let constitutional_hash = seal_bedrock();
    eprintln!("\x1b[32m✓\x1b[0m 5 gates installed");

    // ── Step 3: Persist keys to ~/.zeropoint/keys/ ──────────────
    eprint!("  Writing genesis record...             ");
    let keyring = match Keyring::open(home_zp.join("keys")) {
        Ok(k) => k,
        Err(e) => {
            eprintln!("\x1b[31m✗\x1b[0m");
            eprintln!("  Failed to create keyring: {}", e);
            return 1;
        }
    };

    if let Err(e) = keyring.save_genesis(&genesis, config.store_genesis_secret) {
        eprintln!("\x1b[31m✗\x1b[0m");
        eprintln!("  Failed to save genesis key: {}", e);
        return 1;
    }
    if let Err(e) = keyring.save_operator(&operator) {
        eprintln!("\x1b[31m✗\x1b[0m");
        eprintln!("  Failed to save operator key: {}", e);
        return 1;
    }

    // Write genesis record to ~/.zeropoint/genesis.json
    let genesis_record = serde_json::json!({
        "version": "2.0",
        "timestamp": Utc::now().to_rfc3339(),
        "operator": config.operator_name,
        "genesis_public_key": hex::encode(genesis.public_key()),
        "operator_public_key": hex::encode(operator.public_key()),
        "constitutional_hash": constitutional_hash,
        "algorithm": "Ed25519",
        "audit_chain": "BLAKE3",
        "constitutional_gates": [
            "HarmPrincipleRule",
            "SovereigntyRule",
            "CatastrophicActionRule",
            "BulkOperationRule",
            "ReputationGateRule",
        ],
    });

    let genesis_path = home_zp.join("genesis.json");
    if let Err(e) = std::fs::write(
        &genesis_path,
        serde_json::to_string_pretty(&genesis_record).unwrap(),
    ) {
        eprintln!("\x1b[31m✗\x1b[0m");
        eprintln!("  Failed to write genesis record: {}", e);
        return 1;
    }

    // Create home-level directories for policies and data
    let _ = std::fs::create_dir_all(home_zp.join("policies"));
    let _ = std::fs::create_dir_all(home_zp.join("data"));

    // Also create project-local .zeropoint/ for config and project-specific overrides
    let _ = std::fs::create_dir_all(zp_dir.join("policies"));
    let _ = std::fs::create_dir_all(zp_dir.join("data"));

    eprintln!("\x1b[32m✓\x1b[0m ~/.zeropoint/genesis.json");

    // ── Step 4: Write zeropoint.toml ────────────────────────────
    if !toml_path.exists() {
        let toml_content = format!(
            r#"# ZeroPoint configuration
# Generated by `zp init` on {}

[server]
bind = "127.0.0.1"
port = 3000

[identity]
operator = "{}"
key_path = "~/.zeropoint/keys"

[policy]
# Custom WASM gates, evaluated after constitutional bedrock.
# Add .wasm files to .zeropoint/policies/ and list them here.
gates = []

[audit]
data_dir = ".zeropoint/data"
"#,
            Utc::now().format("%Y-%m-%d"),
            config.operator_name,
        );
        let _ = std::fs::write(&toml_path, toml_content);
    }

    // ── Summary ─────────────────────────────────────────────────
    let genesis_pub = hex::encode(genesis.public_key());
    let short_pub = &genesis_pub[..8];

    eprintln!();
    eprintln!("  Operator identity: \x1b[36m{}...\x1b[0m", short_pub);
    eprintln!(
        "  Constitutional hash: \x1b[36m{}...\x1b[0m",
        &constitutional_hash[..6]
    );
    eprintln!();
    eprintln!("  Your environment is ready.");
    eprintln!("  Run \x1b[1m`zp keys issue`\x1b[0m to create your first agent key.");
    eprintln!();

    0
}

/// Compute a deterministic hash of the constitutional gate set.
///
/// This is a BLAKE3 hash of the canonical gate names, providing a
/// fingerprint that proves which bedrock rules were active at genesis.
fn seal_bedrock() -> String {
    let gates = [
        "HarmPrincipleRule:constitutional",
        "SovereigntyRule:constitutional",
        "CatastrophicActionRule:operational",
        "BulkOperationRule:operational",
        "ReputationGateRule:operational",
    ];
    let content = gates.join("\n");
    let hash = blake3::hash(content.as_bytes());
    hash.to_hex().to_string()
}
