[node]
  enable_node = Yes
  node_name = ZeroPoint
  announce_at_start = Yes
  announce_interval = 360

[client]
  downloads_path = ~/.nomadnetwork/downloads
  user_interface = none

[textui]
  intro_time = 0
  editor = nano
