[reticulum]
  enable_transport = Yes
  share_instance = Yes
  shared_instance_port = 37428
  instance_control_port = 37429
  panic_on_interface_error = No

[interfaces]

  [[Default Interface]]
    type = AutoInterface
    enabled = Yes

  [[RNS Amsterdam Hub]]
    type = TCPClientInterface
    enabled = Yes
    target_host = amsterdam.connect.reticulum.network
    target_port = 4965

  [[RNS BetweenTheBorders Hub]]
    type = TCPClientInterface
    enabled = Yes
    target_host = reticulum.betweentheborders.com
    target_port = 4242
