#!/usr/bin/env bash
# ============================================================================
# ZeroPoint PATH Wrapper — {{TOOL_NAME}}
# ============================================================================
#
# Generated by: zp secure (Phase 3: AI Tool Wrapping)
# Remove by:    Delete this file, or run `zp secure --wizard`
#
# This shim sits in ~/ZeroPoint/bin/ which is first in PATH.
# When {{TOOL_NAME}} is invoked, this script:
#   1. Evaluates the command through ZeroPoint's guard
#   2. If allowed, forwards to the real binary
#   3. If blocked, shows the denial and exits
#
# The wrapped tool doesn't know it's being governed.
# It doesn't need to cooperate. It just becomes accountable.
# ============================================================================

set -euo pipefail

# --- Configuration ---
ZP_BIN="${ZP_BIN:-$HOME/ZeroPoint/bin/zp}"
TOOL_NAME="{{TOOL_NAME}}"
ACTOR="{{ACTOR}}"  # codex for AI coding tools, agent for autonomous

# --- Find the real binary ---
# Skip our own shim by looking for the next match in PATH
_find_real_binary() {
  local self="$HOME/ZeroPoint/bin/$TOOL_NAME"
  local IFS=':'

  for dir in $PATH; do
    local candidate="$dir/$TOOL_NAME"
    # Skip our own shim
    if [[ "$candidate" == "$self" ]]; then
      continue
    fi
    if [[ -x "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  echo "[ZP] Error: real '$TOOL_NAME' binary not found in PATH" >&2
  return 1
}

REAL_BIN=$(_find_real_binary) || exit 1

# --- Guard evaluation ---
# Build the command string for guard evaluation
CMD_STRING="$TOOL_NAME $*"

if [[ -x "$ZP_BIN" ]]; then
  # Evaluate through guard with appropriate actor level
  if ! "$ZP_BIN" guard --actor "$ACTOR" --non-interactive "$CMD_STRING" 2>&1; then
    # Command blocked
    echo "[ZP] Blocked: $CMD_STRING" >&2
    echo "[ZP] Actor: $ACTOR | Run 'zp guard --actor human \"$CMD_STRING\"' to evaluate as human" >&2
    exit 1
  fi
fi

# --- Forward to real binary ---
exec "$REAL_BIN" "$@"
