{
  description = "Pi 5 Sentinel — ZeroPoint substrate node";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";
  };

  outputs = { self, nixpkgs, nixos-hardware, ... }: {
    nixosConfigurations.pi5-sentinel = nixpkgs.lib.nixosSystem {
      system = "aarch64-linux";
      modules = [
        nixos-hardware.nixosModules.raspberry-pi-5
        ./configuration.nix
        # hardware-configuration.nix is generated by nixos-generate-config
        # at install time and dropped alongside this flake — do NOT commit it.
        ./hardware-configuration.nix
      ];
    };
  };
}
