#!/usr/bin/env bash
# verify-check-staleness.sh — trip every branch of the 'just check' staleness
# warning in .githooks/pre-commit, without committing and without changing
# toolchains.
#
# Why this exists (2026-08-17). The warning had no writer: nothing in the tree
# created $GIT_DIR/zp-last-check, so "no recorded successful run" fired on every
# commit forever and the two real detectors — toolchain change, and the 7-day
# age backstop — sat in an else branch that could never be entered. The Justfile
# now stamps the marker. This script confirms that all four states are actually
# distinguishable, rather than trusting that they are.
#
# It is safe to run at any time:
#   - the marker lives in .git/, is untracked, and is regenerated by 'just check'
#   - the hook only reads, runs the pins, and echoes; it mutates nothing
#   - the original marker is saved and restored, including on failure
#
# Usage: bash scripts/verify-check-staleness.sh

set -uo pipefail

cd "$(git rev-parse --show-toplevel)"
GIT_DIR="$(git rev-parse --git-dir)"
MARKER="$GIT_DIR/zp-last-check"
BACKUP="$GIT_DIR/zp-last-check.verify-backup"
NOW_RUSTC="$(rustc --version 2>/dev/null || echo unknown)"

PASS=0
FAIL=0

restore() {
    if [ -f "$BACKUP" ]; then
        cp "$BACKUP" "$MARKER"
        rm -f "$BACKUP"
        echo "marker restored."
    fi
}
trap restore EXIT

if [ -f "$MARKER" ]; then
    cp "$MARKER" "$BACKUP"
else
    echo "note: no marker present — run 'just check' first, then re-run this."
    exit 1
fi

# Run the hook and report whether its output matches what this state should say.
# $1 = state name, $2 = expected substring ("" means: expect no NOTE at all)
probe() {
    state="$1"
    expect="$2"
    out="$(sh .githooks/pre-commit 2>&1 || true)"
    if [ -z "$expect" ]; then
        if printf '%s' "$out" | grep -q "pre-commit: NOTE"; then
            echo "  FAIL  $state — warned when it should have been silent:"
            printf '%s\n' "$out" | grep "pre-commit: NOTE"
            FAIL=$((FAIL + 1))
        else
            echo "  PASS  $state — silent, as it should be"
            PASS=$((PASS + 1))
        fi
    else
        if printf '%s' "$out" | grep -q "$expect"; then
            echo "  PASS  $state — warned: $expect"
            PASS=$((PASS + 1))
        else
            echo "  FAIL  $state — expected a warning containing: $expect"
            printf '%s\n' "$out" | grep "pre-commit: NOTE" || echo "        (no NOTE emitted at all)"
            FAIL=$((FAIL + 1))
        fi
    fi
}

echo "verifying the 'just check' staleness warning — 4 states"
echo

# 1. Current toolchain, fresh marker. This is the state that matters most:
#    if the Justfile writes a rustc string the hook does not reproduce exactly,
#    the warning fires on every commit and is useless in the other direction.
printf '%s\n%s\n' "$NOW_RUSTC" "verification run" > "$MARKER"
probe "fresh marker, same toolchain" ""

# 2. Toolchain changed. The branch the 2026-08-12 comment calls the useful
#    part — ~60 clippy diagnostics accumulated because clippy got newer, not
#    because time passed. One of them was CROSS-USER-01.
printf '%s\n%s\n' "rustc 0.0.0-verification (deadbeef 2020-01-01)" "verification run" > "$MARKER"
probe "toolchain changed" "toolchain changed since the last"

# 3. Same toolchain, marker older than 7 days. A fixed past date avoids
#    date-arithmetic flags that differ between BSD and GNU.
printf '%s\n%s\n' "$NOW_RUSTC" "2026-01-01 00:00 UTC" > "$MARKER"
touch -t 202601010000 "$MARKER"
probe "marker older than 7 days" "over 7 days ago"

# 4. No marker at all — the state the repo was permanently stuck in.
rm -f "$MARKER"
probe "no marker" "no recorded successful run"

echo
echo "$PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
