// crates/zp-keys/src/sovereignty/hardware/mod.rs
//
// Hardware wallet sovereignty providers.
//
// All hardware wallet providers follow the same pattern:
// 1. The Genesis secret is generated by ZeroPoint (Ed25519 seed)
// 2. A wrapping key is derived from the hardware device
// 3. The Genesis secret is encrypted (ChaCha20-Poly1305) with the wrapping key
// 4. The encrypted secret is stored locally in ~/ZeroPoint/sovereignty/
// 5. To load: communicate with the device to re-derive the wrapping key, decrypt
//
// This means the hardware wallet doesn't generate or hold the Genesis key —
// it gates access to it. The key hierarchy stays uniform regardless of device.
//
// The wrapping key derivation varies by device:
// - YubiKey: FIDO2 hmac-secret extension or PIV challenge-response
// - Ledger:  Ledger app derives a key from a BIP-32 path
// - Trezor:  Trezor CipherKeyValue for deterministic key derivation
// - OnlyKey: OnlyKey challenge-response (HMACSHA1 in a slot)

pub mod ledger;
pub mod onlykey;
pub mod trezor;
pub mod yubikey;

use crate::error::KeyError;

/// Shared constant for the encrypted secret file path.
const SOVEREIGNTY_DIR: &str = "sovereignty";

// ---------------------------------------------------------------------------
// Ciphertext version prefixes
// ---------------------------------------------------------------------------
//
// Every encrypted blob written to {mode}_genesis.encrypted is prefixed with
// a single version byte. This allows future crypto migration (e.g., from
// ChaCha20-Poly1305 to AES-256-GCM, or from deterministic to random nonces)
// without breaking existing installs — `decrypt_secret` reads the prefix
// and dispatches to the right decryption path.
//
// Version history:
//   0x01 — ChaCha20-Poly1305, deterministic BLAKE3 nonce (current)

/// Current ciphertext version. Prefixed to every new encrypted blob.
const CIPHERTEXT_VERSION: u8 = 0x01;

// ---------------------------------------------------------------------------
// Timestamped key derivation salt
// ---------------------------------------------------------------------------
//
// When a provider supports CAN_SALTED_DERIVATION, the wrapping key derivation
// can incorporate an epoch-based salt. This means different time periods
// produce different wrapping keys, enabling key rotation without re-genesis:
// re-wrap the secret periodically with a fresh derivation from the same device.
//
// The salt is stored in the enrollment metadata alongside the encrypted blob
// so the correct salt can be supplied during decryption.
//
// Current callers don't use salted derivation yet — the infrastructure is
// here for when providers implement CAN_SALTED_DERIVATION.

/// Optional salt for timestamped/salted wrapping key derivation.
///
/// When present, this is mixed into the wrapping key derivation path
/// so that the same device + same seed produces different wrapping keys
/// at different epochs. Stored alongside the encrypted blob in enrollment
/// metadata so the decryption path knows which salt to supply.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DerivationSalt {
    /// The salt bytes (typically 16-32 bytes).
    pub salt: Vec<u8>,
    /// When this salt was generated (ISO 8601).
    pub created_at: String,
    /// Optional epoch counter for deterministic rotation schedules.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<u64>,
    /// Optional human-readable label (e.g., "monthly-rotation-2026-03").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl DerivationSalt {
    /// Create a new random salt for the current timestamp.
    pub fn generate() -> Self {
        use rand::Rng;
        let mut salt = vec![0u8; 32];
        rand::thread_rng().fill(&mut salt[..]);
        Self {
            salt,
            created_at: chrono::Utc::now().to_rfc3339(),
            epoch: None,
            label: None,
        }
    }

    /// Create a salt with an explicit epoch counter.
    pub fn with_epoch(epoch: u64) -> Self {
        let mut s = Self::generate();
        s.epoch = Some(epoch);
        s
    }

    /// Mix this salt into a wrapping key to produce a salted wrapping key.
    ///
    /// Uses BLAKE3 keyed hash: `BLAKE3(wrapping_key, salt || "zp-salted-wrap-v1")`
    /// The output is a new 32-byte key that's unique per (device, salt) pair.
    pub fn apply(&self, wrapping_key: &[u8; 32]) -> [u8; 32] {
        let mut input = self.salt.clone();
        input.extend_from_slice(b"zp-salted-wrap-v1");
        let hash = blake3::keyed_hash(wrapping_key, &input);
        let mut salted = [0u8; 32];
        salted.copy_from_slice(hash.as_bytes());
        salted
    }
}

/// Encrypt the Genesis secret with a device-derived wrapping key.
///
/// Uses ChaCha20-Poly1305 (same as the vault). The nonce is derived
/// deterministically from BLAKE3(wrapping_key || "zp-hw-wrap-nonce-v1")
/// truncated to 12 bytes.
///
/// The output is: `[version_byte || ciphertext || poly1305_tag]`
/// where version_byte is `CIPHERTEXT_VERSION` (currently 0x01).
pub(crate) fn encrypt_secret(
    secret: &[u8; 32],
    wrapping_key: &[u8; 32],
) -> Result<Vec<u8>, KeyError> {
    use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, KeyInit, Nonce};

    let cipher = ChaCha20Poly1305::new(wrapping_key.into());

    // Deterministic nonce from wrapping key — safe because wrapping key
    // is unique per device and we only encrypt one message with it.
    let nonce_material = blake3::keyed_hash(wrapping_key, b"zp-hw-wrap-nonce-v1");
    let nonce_bytes: [u8; 12] = nonce_material.as_bytes()[..12].try_into().unwrap();
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = cipher
        .encrypt(&nonce, secret.as_ref())
        .map_err(|e| KeyError::CredentialStore(format!("Encryption failed: {}", e)))?;

    // Prepend version byte so future crypto migrations can dispatch correctly
    let mut versioned = Vec::with_capacity(1 + ciphertext.len());
    versioned.push(CIPHERTEXT_VERSION);
    versioned.extend_from_slice(&ciphertext);

    Ok(versioned)
}

/// Decrypt the Genesis secret with a device-derived wrapping key.
///
/// Reads the version prefix byte and dispatches to the correct decryption
/// implementation. Blobs without a version prefix (pre-0.3 format) are
/// handled as legacy v0 — raw ChaCha20-Poly1305 with 48-byte length.
pub(crate) fn decrypt_secret(blob: &[u8], wrapping_key: &[u8; 32]) -> Result<[u8; 32], KeyError> {
    if blob.is_empty() {
        return Err(KeyError::EnrollmentCorrupted(
            "Encrypted secret blob is empty".into(),
        ));
    }

    // Detect version: if first byte is a known version tag, use it.
    // Otherwise, treat the entire blob as legacy (pre-version) format.
    let (version, ciphertext) = match blob[0] {
        CIPHERTEXT_VERSION => (CIPHERTEXT_VERSION, &blob[1..]),
        // Legacy detection: pre-version blobs are exactly 48 bytes
        // (32 encrypted + 16 poly1305 tag). If the blob is 48 bytes and
        // the first byte isn't a known version, it's legacy.
        _ if blob.len() == 48 => {
            tracing::debug!("Decrypting legacy (pre-version) ciphertext blob");
            (0x00, blob)
        }
        unknown => {
            return Err(KeyError::EnrollmentCorrupted(format!(
                "Unknown ciphertext version: 0x{:02x}. \
                 This may require a newer version of ZeroPoint.",
                unknown
            )));
        }
    };

    // Both v0 (legacy) and v1 use the same ChaCha20-Poly1305 scheme
    let _ = version; // reserved for future dispatch
    decrypt_chacha20poly1305(ciphertext, wrapping_key)
}

/// ChaCha20-Poly1305 decryption with deterministic BLAKE3 nonce.
/// Shared by v0 (legacy) and v1 ciphertext formats.
fn decrypt_chacha20poly1305(
    ciphertext: &[u8],
    wrapping_key: &[u8; 32],
) -> Result<[u8; 32], KeyError> {
    use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, KeyInit, Nonce};

    let cipher = ChaCha20Poly1305::new(wrapping_key.into());

    let nonce_material = blake3::keyed_hash(wrapping_key, b"zp-hw-wrap-nonce-v1");
    let nonce_bytes: [u8; 12] = nonce_material.as_bytes()[..12].try_into().unwrap();
    let nonce = Nonce::from(nonce_bytes);

    let plaintext = cipher.decrypt(&nonce, ciphertext).map_err(|_| {
        KeyError::CredentialStore("Decryption failed — wrong device or corrupted data".into())
    })?;

    if plaintext.len() != 32 {
        return Err(KeyError::InvalidKeyMaterial(format!(
            "Decrypted secret has wrong length: {} (expected 32)",
            plaintext.len()
        )));
    }

    let mut secret = [0u8; 32];
    secret.copy_from_slice(&plaintext);
    Ok(secret)
}

/// Get the sovereignty storage directory, creating it if needed.
pub(crate) fn sovereignty_dir() -> Result<std::path::PathBuf, KeyError> {
    let home = zp_core::paths::home()
        .unwrap_or_else(|_| std::path::PathBuf::from("."))
        .join(SOVEREIGNTY_DIR);
    std::fs::create_dir_all(&home)?;
    Ok(home)
}

// ---------------------------------------------------------------------------
// Enrollment data persistence
// ---------------------------------------------------------------------------

/// Versioned enrollment metadata for a hardware wallet provider.
///
/// Stored as JSON at `~/ZeroPoint/sovereignty/{mode}_enrollment.json`.
/// Contains everything needed to re-challenge the device on subsequent loads.
///
/// Quorum-ready: the `share_index` / `quorum_id` / `threshold` fields are
/// reserved for future M-of-N multi-signing support. When a single device
/// gates the entire secret (current 1:1 model), these are all `None`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnrollmentMetadata {
    /// Schema version for forward compatibility.
    pub version: String,
    /// The sovereignty mode this enrollment belongs to.
    pub mode: String,
    /// Device identifier (serial number, credential ID, etc.).
    pub device_id: String,
    /// Human-readable device description (e.g., "Trezor Model T").
    pub device_description: String,
    /// When enrollment was completed.
    pub enrolled_at: String,
    /// Provider-specific opaque data (e.g., BIP-32 path, FIDO2 credential).
    #[serde(default, skip_serializing_if = "serde_json::Value::is_null")]
    pub provider_data: serde_json::Value,

    // ── Attestation (v0.3+) ─────────────────────────────────────
    /// Raw device attestation blob, if the device supports it.
    ///
    /// For FIDO2 devices this is the attestation statement from the
    /// credential creation response. For Trezor/Ledger this may be
    /// firmware signature data. Stored as hex-encoded bytes.
    ///
    /// Capturing this now (even empty) ensures we have the field in
    /// all enrollment files when we later need it for quorum auditing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attestation: Option<String>,

    // ── Quorum-ready fields (reserved for M-of-N) ───────────────
    /// Which Shamir share this device holds (0-indexed).
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub share_index: Option<u8>,

    /// Opaque quorum identifier linking all devices in a quorum group.
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quorum_id: Option<String>,

    /// M-of-N threshold for the quorum this device belongs to.
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threshold: Option<QuorumThreshold>,
}

/// M-of-N quorum threshold configuration.
///
/// Reserved for future multi-signing support. When implemented,
/// the Genesis secret will be split via Shamir Secret Sharing
/// across N devices, requiring M devices to reconstruct.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct QuorumThreshold {
    /// Minimum number of devices needed to reconstruct the secret.
    pub required: u8,
    /// Total number of shares (devices) in the quorum.
    pub total: u8,
}

/// Save enrollment metadata for a hardware wallet provider.
pub(crate) fn save_enrollment(metadata: &EnrollmentMetadata) -> Result<(), KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_enrollment.json", metadata.mode);
    let json = serde_json::to_string_pretty(metadata)
        .map_err(|e| KeyError::Serialization(e.to_string()))?;
    std::fs::write(dir.join(&filename), json)?;
    Ok(())
}

/// Load enrollment metadata for a hardware wallet provider.
pub(crate) fn load_enrollment(mode: &str) -> Result<EnrollmentMetadata, KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_enrollment.json", mode);
    let path = dir.join(&filename);
    if !path.exists() {
        return Err(KeyError::NotEnrolled(format!(
            "No enrollment data found for {}. Run the Genesis ceremony to enroll.",
            mode
        )));
    }
    let json = std::fs::read_to_string(&path)?;
    serde_json::from_str(&json).map_err(|e| {
        KeyError::EnrollmentCorrupted(format!("{} enrollment data is corrupted: {}", mode, e))
    })
}

// ---------------------------------------------------------------------------
// Encrypted secret file I/O
// ---------------------------------------------------------------------------

/// Save an encrypted Genesis secret blob for a hardware wallet provider.
///
/// The ciphertext is the output of `encrypt_secret()` — ChaCha20-Poly1305
/// authenticated ciphertext (48 bytes: 32 encrypted + 16 tag).
pub(crate) fn save_encrypted_secret(mode: &str, ciphertext: &[u8]) -> Result<(), KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    std::fs::write(dir.join(&filename), ciphertext)?;
    Ok(())
}

/// Load an encrypted Genesis secret blob for a hardware wallet provider.
pub(crate) fn load_encrypted_secret(mode: &str) -> Result<Vec<u8>, KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    let path = dir.join(&filename);
    if !path.exists() {
        return Err(KeyError::NotEnrolled(format!(
            "No encrypted secret found for {}. Run the Genesis ceremony first.",
            mode
        )));
    }
    let data = std::fs::read(&path)?;
    if data.is_empty() {
        return Err(KeyError::EnrollmentCorrupted(format!(
            "{} encrypted secret file is empty",
            mode
        )));
    }
    Ok(data)
}

// ---------------------------------------------------------------------------
// Provider rotation (rewrap)
// ---------------------------------------------------------------------------

/// Re-wrap the Genesis secret from one wrapping key to another.
///
/// This is the core primitive for provider rotation without re-genesis:
/// decrypt with the old device's key, re-encrypt with the new device's key,
/// and atomically replace the encrypted blob on disk.
///
/// The caller is responsible for:
/// 1. Deriving both wrapping keys (old and new) from their respective devices
/// 2. Updating the enrollment metadata to reflect the new device
/// 3. Signing a rotation record in the ceremony transcript
///
/// Returns the new ciphertext (already persisted to disk).
pub fn rewrap_secret(
    mode: &str,
    old_wrapping_key: &[u8; 32],
    new_wrapping_key: &[u8; 32],
) -> Result<Vec<u8>, KeyError> {
    // Load + decrypt with old key
    let old_blob = load_encrypted_secret(mode)?;
    let secret = decrypt_secret(&old_blob, old_wrapping_key)?;

    // Re-encrypt with new key (includes version prefix)
    let new_blob = encrypt_secret(&secret, new_wrapping_key)?;

    // Atomic-ish write: write to .tmp, then rename
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    let tmp_path = dir.join(format!("{}.tmp", filename));
    let final_path = dir.join(&filename);

    std::fs::write(&tmp_path, &new_blob)?;
    std::fs::rename(&tmp_path, &final_path)?;

    tracing::info!(
        mode = %mode,
        "Genesis secret re-wrapped with new wrapping key"
    );

    // Note: `secret` is [u8; 32] (Copy type) — it will be dropped when it
    // goes out of scope. For production hardening, consider using `zeroize`
    // crate with a `Zeroizing<[u8; 32]>` wrapper to guarantee scrubbing.

    Ok(new_blob)
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ── Helper: generate a deterministic wrapping key for testing ────
    fn test_wrapping_key(seed: u8) -> [u8; 32] {
        let mut key = [0u8; 32];
        for (i, b) in key.iter_mut().enumerate() {
            *b = seed.wrapping_add(i as u8);
        }
        key
    }

    fn test_secret() -> [u8; 32] {
        let mut s = [0u8; 32];
        for (i, b) in s.iter_mut().enumerate() {
            *b = 0xAA ^ (i as u8);
        }
        s
    }

    // ── Encrypt / Decrypt roundtrip ─────────────────────────────────

    #[test]
    fn encrypt_decrypt_roundtrip() {
        let secret = test_secret();
        let key = test_wrapping_key(0x01);

        let blob = encrypt_secret(&secret, &key).unwrap();
        let recovered = decrypt_secret(&blob, &key).unwrap();

        assert_eq!(secret, recovered);
    }

    #[test]
    fn encrypt_produces_versioned_blob() {
        let secret = test_secret();
        let key = test_wrapping_key(0x02);

        let blob = encrypt_secret(&secret, &key).unwrap();

        // First byte is version prefix
        assert_eq!(blob[0], CIPHERTEXT_VERSION);
        // ChaCha20-Poly1305: 32 plaintext → 32 ciphertext + 16 tag = 48
        // Plus 1 version byte = 49
        assert_eq!(blob.len(), 49);
    }

    #[test]
    fn decrypt_rejects_wrong_wrapping_key() {
        let secret = test_secret();
        let key_a = test_wrapping_key(0x01);
        let key_b = test_wrapping_key(0x02);

        let blob = encrypt_secret(&secret, &key_a).unwrap();
        let result = decrypt_secret(&blob, &key_b);

        assert!(result.is_err());
        let err_msg = format!("{}", result.unwrap_err());
        assert!(
            err_msg.contains("wrong device") || err_msg.contains("Decryption failed"),
            "Unexpected error: {}",
            err_msg
        );
    }

    #[test]
    fn decrypt_rejects_empty_blob() {
        let key = test_wrapping_key(0x01);
        let result = decrypt_secret(&[], &key);
        assert!(result.is_err());
        assert!(
            format!("{}", result.unwrap_err()).contains("empty"),
            "Expected 'empty' in error"
        );
    }

    #[test]
    fn decrypt_rejects_unknown_version() {
        let key = test_wrapping_key(0x01);
        // Version 0xFF, followed by enough bytes to not be legacy (> 48 total)
        let mut bad_blob = vec![0xFF];
        bad_blob.extend_from_slice(&[0u8; 60]);

        let result = decrypt_secret(&bad_blob, &key);
        assert!(result.is_err());
        assert!(
            format!("{}", result.unwrap_err()).contains("Unknown ciphertext version"),
            "Expected version error"
        );
    }

    #[test]
    fn decrypt_handles_legacy_48_byte_blob() {
        // Legacy (pre-version) format: raw 48-byte ChaCha20-Poly1305 output
        // with no version prefix. We construct one manually.
        let secret = test_secret();
        let key = test_wrapping_key(0x03);

        // Build a legacy blob by encrypting and stripping the version byte
        let versioned = encrypt_secret(&secret, &key).unwrap();
        let legacy = &versioned[1..]; // strip version byte
        assert_eq!(legacy.len(), 48);

        // decrypt_secret should detect legacy format (48 bytes, first byte != known version)
        let recovered = decrypt_secret(legacy, &key).unwrap();
        assert_eq!(secret, recovered);
    }

    // ── Deterministic nonce ─────────────────────────────────────────

    #[test]
    fn encrypt_is_deterministic_for_same_key() {
        let secret = test_secret();
        let key = test_wrapping_key(0x04);

        let blob_a = encrypt_secret(&secret, &key).unwrap();
        let blob_b = encrypt_secret(&secret, &key).unwrap();

        // Same key + same secret → same ciphertext (deterministic nonce)
        assert_eq!(blob_a, blob_b);
    }

    #[test]
    fn different_keys_produce_different_ciphertexts() {
        let secret = test_secret();
        let key_a = test_wrapping_key(0x05);
        let key_b = test_wrapping_key(0x06);

        let blob_a = encrypt_secret(&secret, &key_a).unwrap();
        let blob_b = encrypt_secret(&secret, &key_b).unwrap();

        assert_ne!(blob_a, blob_b);
    }

    // ── DerivationSalt ──────────────────────────────────────────────

    #[test]
    fn derivation_salt_generate_produces_32_bytes() {
        let salt = DerivationSalt::generate();
        assert_eq!(salt.salt.len(), 32);
        assert!(salt.epoch.is_none());
    }

    #[test]
    fn derivation_salt_with_epoch() {
        let salt = DerivationSalt::with_epoch(42);
        assert_eq!(salt.epoch, Some(42));
    }

    #[test]
    fn derivation_salt_apply_changes_key() {
        let key = test_wrapping_key(0x07);
        let salt = DerivationSalt::generate();

        let salted = salt.apply(&key);
        assert_ne!(key, salted);
    }

    #[test]
    fn derivation_salt_apply_is_deterministic() {
        let key = test_wrapping_key(0x08);
        let salt = DerivationSalt {
            salt: vec![0xBB; 32],
            created_at: "2026-04-18T00:00:00Z".into(),
            epoch: None,
            label: None,
        };

        let a = salt.apply(&key);
        let b = salt.apply(&key);
        assert_eq!(a, b);
    }

    #[test]
    fn different_salts_produce_different_keys() {
        let key = test_wrapping_key(0x09);

        let salt_a = DerivationSalt {
            salt: vec![0xAA; 32],
            created_at: "2026-04-18T00:00:00Z".into(),
            epoch: None,
            label: None,
        };
        let salt_b = DerivationSalt {
            salt: vec![0xBB; 32],
            created_at: "2026-04-18T00:00:00Z".into(),
            epoch: None,
            label: None,
        };

        assert_ne!(salt_a.apply(&key), salt_b.apply(&key));
    }

    #[test]
    fn salted_encrypt_decrypt_roundtrip() {
        let secret = test_secret();
        let base_key = test_wrapping_key(0x0A);
        let salt = DerivationSalt::generate();

        let salted_key = salt.apply(&base_key);
        let blob = encrypt_secret(&secret, &salted_key).unwrap();
        let recovered = decrypt_secret(&blob, &salted_key).unwrap();

        assert_eq!(secret, recovered);
    }

    #[test]
    fn salted_key_cannot_decrypt_unsalted_blob() {
        let secret = test_secret();
        let base_key = test_wrapping_key(0x0B);
        let salt = DerivationSalt::generate();
        let salted_key = salt.apply(&base_key);

        // Encrypt with base key
        let blob = encrypt_secret(&secret, &base_key).unwrap();
        // Try to decrypt with salted key — should fail
        assert!(decrypt_secret(&blob, &salted_key).is_err());
    }

    // ── EnrollmentMetadata serialization ─────────────────────────────

    #[test]
    fn enrollment_metadata_serde_roundtrip() {
        let meta = EnrollmentMetadata {
            version: "2".into(),
            mode: "trezor".into(),
            device_id: "My Trezor".into(),
            device_description: "Trezor Model T".into(),
            enrolled_at: "2026-04-18T12:00:00Z".into(),
            provider_data: serde_json::json!({
                "path": "m/10016'/0",
                "key_name": "ZeroPoint Genesis",
            }),
            attestation: None,
            share_index: None,
            quorum_id: None,
            threshold: None,
        };

        let json = serde_json::to_string_pretty(&meta).unwrap();
        let parsed: EnrollmentMetadata = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.version, "2");
        assert_eq!(parsed.mode, "trezor");
        assert_eq!(parsed.device_id, "My Trezor");
        assert!(parsed.attestation.is_none());
        assert!(parsed.share_index.is_none());
    }

    #[test]
    fn enrollment_metadata_with_quorum_fields() {
        let meta = EnrollmentMetadata {
            version: "2".into(),
            mode: "trezor".into(),
            device_id: "Device A".into(),
            device_description: "Trezor for quorum".into(),
            enrolled_at: "2026-04-18T12:00:00Z".into(),
            provider_data: serde_json::Value::Null,
            attestation: Some("deadbeef".into()),
            share_index: Some(0),
            quorum_id: Some("quorum-123".into()),
            threshold: Some(QuorumThreshold {
                required: 2,
                total: 3,
            }),
        };

        let json = serde_json::to_string_pretty(&meta).unwrap();
        let parsed: EnrollmentMetadata = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.share_index, Some(0));
        assert_eq!(parsed.quorum_id.as_deref(), Some("quorum-123"));
        let t = parsed.threshold.unwrap();
        assert_eq!(t.required, 2);
        assert_eq!(t.total, 3);
    }

    #[test]
    fn enrollment_metadata_missing_optional_fields_deserializes() {
        // Minimal JSON — simulates a v1 enrollment file without quorum fields
        let json = r#"{
            "version": "1",
            "mode": "ledger",
            "device_id": "Ledger Nano",
            "device_description": "Ledger Nano X",
            "enrolled_at": "2026-01-01T00:00:00Z",
            "provider_data": null
        }"#;

        let parsed: EnrollmentMetadata = serde_json::from_str(json).unwrap();
        assert_eq!(parsed.version, "1");
        assert!(parsed.attestation.is_none());
        assert!(parsed.share_index.is_none());
        assert!(parsed.quorum_id.is_none());
        assert!(parsed.threshold.is_none());
    }

    // ── Rewrap ──────────────────────────────────────────────────────

    #[test]
    fn rewrap_secret_changes_ciphertext() {
        let secret = test_secret();
        let old_key = test_wrapping_key(0x0C);
        let new_key = test_wrapping_key(0x0D);

        // Simulate: save encrypted blob with old key
        let old_blob = encrypt_secret(&secret, &old_key).unwrap();

        // Create temp dir to simulate sovereignty_dir
        let tmp = tempfile::tempdir().unwrap();
        let sov_dir = tmp.path().join(".zeropoint").join("sovereignty");
        std::fs::create_dir_all(&sov_dir).unwrap();

        std::fs::write(sov_dir.join("test_genesis.encrypted"), &old_blob).unwrap();

        // Verify old key decrypts
        let loaded = std::fs::read(sov_dir.join("test_genesis.encrypted")).unwrap();
        let recovered = decrypt_secret(&loaded, &old_key).unwrap();
        assert_eq!(secret, recovered);

        // Verify new key does NOT decrypt old blob
        assert!(decrypt_secret(&loaded, &new_key).is_err());

        // Manually re-encrypt (rewrap_secret uses sovereignty_dir() which
        // points to real HOME — test the core logic instead)
        let new_blob = encrypt_secret(&recovered, &new_key).unwrap();
        assert_ne!(old_blob, new_blob);

        // Verify new key decrypts new blob
        let final_secret = decrypt_secret(&new_blob, &new_key).unwrap();
        assert_eq!(secret, final_secret);
    }

    // ── File I/O ────────────────────────────────────────────────────

    #[test]
    fn load_encrypted_secret_returns_not_enrolled_when_missing() {
        // This test uses the real sovereignty_dir() pointed at HOME,
        // but checks for a mode name that should never exist
        let result = load_encrypted_secret("__nonexistent_test_mode__");
        assert!(result.is_err());
        assert!(
            format!("{}", result.unwrap_err()).contains("No encrypted secret found"),
            "Expected 'No encrypted secret found' error"
        );
    }

    #[test]
    fn load_enrollment_returns_not_enrolled_when_missing() {
        let result = load_enrollment("__nonexistent_test_mode__");
        assert!(result.is_err());
        assert!(
            format!("{}", result.unwrap_err()).contains("No enrollment data found"),
            "Expected 'No enrollment data found' error"
        );
    }

    // ── Provider status and ceremony readiness ──────────────────────

    #[test]
    fn detection_only_providers_are_not_ceremony_ready() {
        use super::super::SovereigntyMode;

        let detection_only = [
            SovereigntyMode::YubiKey,
            SovereigntyMode::Ledger,
            SovereigntyMode::OnlyKey,
        ];

        for mode in &detection_only {
            assert_eq!(
                mode.implementation_status(),
                super::super::ProviderStatus::DetectionOnly,
                "{:?} should be DetectionOnly",
                mode
            );
            assert!(
                !mode.is_ceremony_ready(),
                "{:?} should NOT be ceremony-ready",
                mode
            );
        }
    }

    #[test]
    fn trezor_ceremony_readiness_depends_on_feature() {
        use super::super::SovereigntyMode;

        let status = SovereigntyMode::Trezor.implementation_status();
        if cfg!(feature = "hw-trezor") {
            assert_eq!(status, super::super::ProviderStatus::Ready);
            assert!(SovereigntyMode::Trezor.is_ceremony_ready());
        } else {
            assert_eq!(status, super::super::ProviderStatus::DetectionOnly);
            assert!(!SovereigntyMode::Trezor.is_ceremony_ready());
        }
    }

    #[test]
    fn all_hw_providers_require_external_device() {
        use super::super::SovereigntyMode;

        assert!(SovereigntyMode::YubiKey.requires_external_device());
        assert!(SovereigntyMode::Ledger.requires_external_device());
        assert!(SovereigntyMode::Trezor.requires_external_device());
        assert!(SovereigntyMode::OnlyKey.requires_external_device());
    }

    #[test]
    fn hw_providers_are_hardware_category() {
        use super::super::{SovereigntyCategory, SovereigntyMode};

        assert_eq!(SovereigntyMode::YubiKey.category(), SovereigntyCategory::HardwareWallet);
        assert_eq!(SovereigntyMode::Ledger.category(), SovereigntyCategory::HardwareWallet);
        assert_eq!(SovereigntyMode::Trezor.category(), SovereigntyCategory::HardwareWallet);
        assert_eq!(SovereigntyMode::OnlyKey.category(), SovereigntyCategory::HardwareWallet);
    }

    // ── Stub providers return correct errors ────────────────────────

    #[test]
    fn ledger_stub_returns_not_implemented() {
        use super::super::SovereigntyProvider;

        let provider = ledger::LedgerProvider;
        assert!(provider.save_secret(&[0u8; 32]).is_err());
        assert!(provider.load_secret().is_err());
        assert!(provider.verify_presence().is_err());
        assert!(provider.enroll().is_err());

        let err = format!("{}", provider.save_secret(&[0u8; 32]).unwrap_err());
        assert!(err.contains("v0.3"), "Expected v0.3 mention: {}", err);
    }

    #[test]
    fn onlykey_stub_returns_not_implemented() {
        use super::super::SovereigntyProvider;

        let provider = onlykey::OnlyKeyProvider;
        assert!(provider.save_secret(&[0u8; 32]).is_err());
        assert!(provider.load_secret().is_err());
        assert!(provider.verify_presence().is_err());
        assert!(provider.enroll().is_err());
    }

    #[test]
    fn yubikey_stub_returns_feature_required() {
        use super::super::SovereigntyProvider;

        let provider = yubikey::YubiKeyProvider;
        let err = format!("{}", provider.save_secret(&[0u8; 32]).unwrap_err());
        // Should mention the feature flag or v0.3
        assert!(
            err.contains("hw-yubikey") || err.contains("v0.3"),
            "Expected feature/version mention: {}",
            err
        );
    }

    #[test]
    fn trezor_without_feature_returns_not_implemented() {
        use super::super::SovereigntyProvider;

        if cfg!(feature = "hw-trezor") {
            // Can't test the stub path when feature is enabled
            return;
        }

        let provider = trezor::TrezorProvider;
        assert!(provider.verify_presence().is_err());
        assert!(provider.enroll().is_err());

        let err = format!("{}", provider.verify_presence().unwrap_err());
        assert!(
            err.contains("hw-trezor"),
            "Expected feature flag mention: {}",
            err
        );
    }

    // ── Trezor capabilities ─────────────────────────────────────────

    #[test]
    fn trezor_has_rewrap_capability() {
        use super::super::{ProviderCapabilities, SovereigntyProvider};

        let provider = trezor::TrezorProvider;
        let caps = provider.capabilities();
        assert!(caps.has(ProviderCapabilities::CAN_REWRAP));
    }

    // ── Detection description consistency ────────────────────────────

    #[test]
    fn detection_only_descriptions_do_not_say_connect_device() {
        use super::super::SovereigntyProvider;

        // These providers are stubs — their descriptions should NOT tell
        // users to connect a device, because that won't help.
        let stubs: Vec<Box<dyn SovereigntyProvider>> = vec![
            Box::new(ledger::LedgerProvider),
            Box::new(onlykey::OnlyKeyProvider),
        ];

        for provider in &stubs {
            let cap = provider.detect();
            if cap.implementation_status == super::super::ProviderStatus::DetectionOnly && !cap.available {
                assert!(
                    !cap.description.to_lowercase().contains("connect your"),
                    "{:?} says 'connect your' but is DetectionOnly: {:?}",
                    provider.mode(),
                    cap.description
                );
            }
        }
    }

    #[test]
    fn yubikey_detection_only_description_is_honest() {
        use super::super::SovereigntyProvider;

        if cfg!(feature = "hw-yubikey") {
            return; // Feature enabled — not a stub
        }

        let cap = yubikey::YubiKeyProvider.detect();
        if !cap.available {
            // Should mention feature flag or version, not "insert your YubiKey"
            assert!(
                !cap.description.contains("insert your"),
                "YubiKey DetectionOnly description should not say 'insert': {}",
                cap.description
            );
        }
    }

    #[test]
    fn trezor_detection_only_description_is_honest() {
        use super::super::SovereigntyProvider;

        if cfg!(feature = "hw-trezor") {
            return; // Feature enabled — full support
        }

        let cap = trezor::TrezorProvider.detect();
        if !cap.available {
            assert!(
                !cap.description.to_lowercase().contains("connect your"),
                "Trezor DetectionOnly description should not say 'connect your': {}",
                cap.description
            );
        }
    }

    // ── provider_for dispatch ───────────────────────────────────────

    #[test]
    fn provider_for_returns_correct_mode() {
        use super::super::{provider_for, SovereigntyMode};

        let modes = [
            SovereigntyMode::TouchId,
            SovereigntyMode::Fingerprint,
            SovereigntyMode::LoginPassword,
            SovereigntyMode::FileBased,
            SovereigntyMode::YubiKey,
            SovereigntyMode::Ledger,
            SovereigntyMode::Trezor,
            SovereigntyMode::OnlyKey,
        ];

        for mode in &modes {
            let provider = provider_for(*mode);
            assert_eq!(
                provider.mode(),
                *mode,
                "provider_for({:?}) returned wrong mode",
                mode
            );
        }
    }

    #[test]
    fn legacy_biometric_resolves_to_concrete_provider() {
        use super::super::{provider_for, SovereigntyMode};

        let provider = provider_for(SovereigntyMode::LegacyBiometric);
        // Should resolve to TouchId on macOS, Fingerprint on Linux, etc.
        let mode = provider.mode();
        assert_ne!(
            mode,
            SovereigntyMode::LegacyBiometric,
            "LegacyBiometric should resolve to a concrete provider"
        );
    }

    // ── from_onboard_str for hardware modes ─────────────────────────

    #[test]
    fn from_onboard_str_parses_hardware_modes() {
        use super::super::SovereigntyMode;

        assert_eq!(SovereigntyMode::from_onboard_str("trezor"), SovereigntyMode::Trezor);
        assert_eq!(SovereigntyMode::from_onboard_str("ledger"), SovereigntyMode::Ledger);
        assert_eq!(SovereigntyMode::from_onboard_str("yubikey"), SovereigntyMode::YubiKey);
        assert_eq!(SovereigntyMode::from_onboard_str("yubi-key"), SovereigntyMode::YubiKey);
        assert_eq!(SovereigntyMode::from_onboard_str("yubi_key"), SovereigntyMode::YubiKey);
        assert_eq!(SovereigntyMode::from_onboard_str("onlykey"), SovereigntyMode::OnlyKey);
        assert_eq!(SovereigntyMode::from_onboard_str("only-key"), SovereigntyMode::OnlyKey);
        assert_eq!(SovereigntyMode::from_onboard_str("only_key"), SovereigntyMode::OnlyKey);
    }

    #[test]
    fn from_onboard_str_unknown_falls_back_to_login_password() {
        use super::super::SovereigntyMode;
        assert_eq!(
            SovereigntyMode::from_onboard_str("nonexistent"),
            SovereigntyMode::LoginPassword
        );
    }
}
