// crates/zp-keys/src/sovereignty/hardware/mod.rs
//
// Hardware wallet sovereignty providers.
//
// All hardware wallet providers follow the same pattern:
// 1. The Genesis secret is generated by ZeroPoint (Ed25519 seed)
// 2. A wrapping key is derived from the hardware device
// 3. The Genesis secret is encrypted (ChaCha20-Poly1305) with the wrapping key
// 4. The encrypted secret is stored locally in ~/.zeropoint/sovereignty/
// 5. To load: communicate with the device to re-derive the wrapping key, decrypt
//
// This means the hardware wallet doesn't generate or hold the Genesis key —
// it gates access to it. The key hierarchy stays uniform regardless of device.
//
// The wrapping key derivation varies by device:
// - YubiKey: FIDO2 hmac-secret extension or PIV challenge-response
// - Ledger:  Ledger app derives a key from a BIP-32 path
// - Trezor:  Trezor CipherKeyValue for deterministic key derivation
// - OnlyKey: OnlyKey challenge-response (HMACSHA1 in a slot)

pub mod ledger;
pub mod onlykey;
pub mod trezor;
pub mod yubikey;

use crate::error::KeyError;

/// Shared constant for the encrypted secret file path.
const SOVEREIGNTY_DIR: &str = "sovereignty";

// ---------------------------------------------------------------------------
// Ciphertext version prefixes
// ---------------------------------------------------------------------------
//
// Every encrypted blob written to {mode}_genesis.encrypted is prefixed with
// a single version byte. This allows future crypto migration (e.g., from
// ChaCha20-Poly1305 to AES-256-GCM, or from deterministic to random nonces)
// without breaking existing installs — `decrypt_secret` reads the prefix
// and dispatches to the right decryption path.
//
// Version history:
//   0x01 — ChaCha20-Poly1305, deterministic BLAKE3 nonce (current)

/// Current ciphertext version. Prefixed to every new encrypted blob.
const CIPHERTEXT_VERSION: u8 = 0x01;

// ---------------------------------------------------------------------------
// Timestamped key derivation salt
// ---------------------------------------------------------------------------
//
// When a provider supports CAN_SALTED_DERIVATION, the wrapping key derivation
// can incorporate an epoch-based salt. This means different time periods
// produce different wrapping keys, enabling key rotation without re-genesis:
// re-wrap the secret periodically with a fresh derivation from the same device.
//
// The salt is stored in the enrollment metadata alongside the encrypted blob
// so the correct salt can be supplied during decryption.
//
// Current callers don't use salted derivation yet — the infrastructure is
// here for when providers implement CAN_SALTED_DERIVATION.

/// Optional salt for timestamped/salted wrapping key derivation.
///
/// When present, this is mixed into the wrapping key derivation path
/// so that the same device + same seed produces different wrapping keys
/// at different epochs. Stored alongside the encrypted blob in enrollment
/// metadata so the decryption path knows which salt to supply.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DerivationSalt {
    /// The salt bytes (typically 16-32 bytes).
    pub salt: Vec<u8>,
    /// When this salt was generated (ISO 8601).
    pub created_at: String,
    /// Optional epoch counter for deterministic rotation schedules.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub epoch: Option<u64>,
    /// Optional human-readable label (e.g., "monthly-rotation-2026-03").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
}

impl DerivationSalt {
    /// Create a new random salt for the current timestamp.
    pub fn generate() -> Self {
        use rand::Rng;
        let mut salt = vec![0u8; 32];
        rand::thread_rng().fill(&mut salt[..]);
        Self {
            salt,
            created_at: chrono::Utc::now().to_rfc3339(),
            epoch: None,
            label: None,
        }
    }

    /// Create a salt with an explicit epoch counter.
    pub fn with_epoch(epoch: u64) -> Self {
        let mut s = Self::generate();
        s.epoch = Some(epoch);
        s
    }

    /// Mix this salt into a wrapping key to produce a salted wrapping key.
    ///
    /// Uses BLAKE3 keyed hash: `BLAKE3(wrapping_key, salt || "zp-salted-wrap-v1")`
    /// The output is a new 32-byte key that's unique per (device, salt) pair.
    pub fn apply(&self, wrapping_key: &[u8; 32]) -> [u8; 32] {
        let mut input = self.salt.clone();
        input.extend_from_slice(b"zp-salted-wrap-v1");
        let hash = blake3::keyed_hash(wrapping_key, &input);
        let mut salted = [0u8; 32];
        salted.copy_from_slice(hash.as_bytes());
        salted
    }
}

/// Encrypt the Genesis secret with a device-derived wrapping key.
///
/// Uses ChaCha20-Poly1305 (same as the vault). The nonce is derived
/// deterministically from BLAKE3(wrapping_key || "zp-hw-wrap-nonce-v1")
/// truncated to 12 bytes.
///
/// The output is: `[version_byte || ciphertext || poly1305_tag]`
/// where version_byte is `CIPHERTEXT_VERSION` (currently 0x01).
pub(crate) fn encrypt_secret(
    secret: &[u8; 32],
    wrapping_key: &[u8; 32],
) -> Result<Vec<u8>, KeyError> {
    use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, KeyInit, Nonce};

    let cipher = ChaCha20Poly1305::new(wrapping_key.into());

    // Deterministic nonce from wrapping key — safe because wrapping key
    // is unique per device and we only encrypt one message with it.
    let nonce_material = blake3::keyed_hash(wrapping_key, b"zp-hw-wrap-nonce-v1");
    let nonce_bytes: [u8; 12] = nonce_material.as_bytes()[..12].try_into().unwrap();
    let nonce = Nonce::from(nonce_bytes);

    let ciphertext = cipher
        .encrypt(&nonce, secret.as_ref())
        .map_err(|e| KeyError::CredentialStore(format!("Encryption failed: {}", e)))?;

    // Prepend version byte so future crypto migrations can dispatch correctly
    let mut versioned = Vec::with_capacity(1 + ciphertext.len());
    versioned.push(CIPHERTEXT_VERSION);
    versioned.extend_from_slice(&ciphertext);

    Ok(versioned)
}

/// Decrypt the Genesis secret with a device-derived wrapping key.
///
/// Reads the version prefix byte and dispatches to the correct decryption
/// implementation. Blobs without a version prefix (pre-0.3 format) are
/// handled as legacy v0 — raw ChaCha20-Poly1305 with 48-byte length.
pub(crate) fn decrypt_secret(blob: &[u8], wrapping_key: &[u8; 32]) -> Result<[u8; 32], KeyError> {
    if blob.is_empty() {
        return Err(KeyError::EnrollmentCorrupted(
            "Encrypted secret blob is empty".into(),
        ));
    }

    // Detect version: if first byte is a known version tag, use it.
    // Otherwise, treat the entire blob as legacy (pre-version) format.
    let (version, ciphertext) = match blob[0] {
        CIPHERTEXT_VERSION => (CIPHERTEXT_VERSION, &blob[1..]),
        // Legacy detection: pre-version blobs are exactly 48 bytes
        // (32 encrypted + 16 poly1305 tag). If the blob is 48 bytes and
        // the first byte isn't a known version, it's legacy.
        _ if blob.len() == 48 => {
            tracing::debug!("Decrypting legacy (pre-version) ciphertext blob");
            (0x00, blob)
        }
        unknown => {
            return Err(KeyError::EnrollmentCorrupted(format!(
                "Unknown ciphertext version: 0x{:02x}. \
                 This may require a newer version of ZeroPoint.",
                unknown
            )));
        }
    };

    // Both v0 (legacy) and v1 use the same ChaCha20-Poly1305 scheme
    let _ = version; // reserved for future dispatch
    decrypt_chacha20poly1305(ciphertext, wrapping_key)
}

/// ChaCha20-Poly1305 decryption with deterministic BLAKE3 nonce.
/// Shared by v0 (legacy) and v1 ciphertext formats.
fn decrypt_chacha20poly1305(
    ciphertext: &[u8],
    wrapping_key: &[u8; 32],
) -> Result<[u8; 32], KeyError> {
    use chacha20poly1305::{aead::Aead, ChaCha20Poly1305, KeyInit, Nonce};

    let cipher = ChaCha20Poly1305::new(wrapping_key.into());

    let nonce_material = blake3::keyed_hash(wrapping_key, b"zp-hw-wrap-nonce-v1");
    let nonce_bytes: [u8; 12] = nonce_material.as_bytes()[..12].try_into().unwrap();
    let nonce = Nonce::from(nonce_bytes);

    let plaintext = cipher.decrypt(&nonce, ciphertext).map_err(|_| {
        KeyError::CredentialStore("Decryption failed — wrong device or corrupted data".into())
    })?;

    if plaintext.len() != 32 {
        return Err(KeyError::InvalidKeyMaterial(format!(
            "Decrypted secret has wrong length: {} (expected 32)",
            plaintext.len()
        )));
    }

    let mut secret = [0u8; 32];
    secret.copy_from_slice(&plaintext);
    Ok(secret)
}

/// Get the sovereignty storage directory, creating it if needed.
pub(crate) fn sovereignty_dir() -> Result<std::path::PathBuf, KeyError> {
    let home = dirs::home_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join(".zeropoint")
        .join(SOVEREIGNTY_DIR);
    std::fs::create_dir_all(&home)?;
    Ok(home)
}

// ---------------------------------------------------------------------------
// Enrollment data persistence
// ---------------------------------------------------------------------------

/// Versioned enrollment metadata for a hardware wallet provider.
///
/// Stored as JSON at `~/.zeropoint/sovereignty/{mode}_enrollment.json`.
/// Contains everything needed to re-challenge the device on subsequent loads.
///
/// Quorum-ready: the `share_index` / `quorum_id` / `threshold` fields are
/// reserved for future M-of-N multi-signing support. When a single device
/// gates the entire secret (current 1:1 model), these are all `None`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EnrollmentMetadata {
    /// Schema version for forward compatibility.
    pub version: String,
    /// The sovereignty mode this enrollment belongs to.
    pub mode: String,
    /// Device identifier (serial number, credential ID, etc.).
    pub device_id: String,
    /// Human-readable device description (e.g., "Trezor Model T").
    pub device_description: String,
    /// When enrollment was completed.
    pub enrolled_at: String,
    /// Provider-specific opaque data (e.g., BIP-32 path, FIDO2 credential).
    #[serde(default, skip_serializing_if = "serde_json::Value::is_null")]
    pub provider_data: serde_json::Value,

    // ── Attestation (v0.3+) ─────────────────────────────────────
    /// Raw device attestation blob, if the device supports it.
    ///
    /// For FIDO2 devices this is the attestation statement from the
    /// credential creation response. For Trezor/Ledger this may be
    /// firmware signature data. Stored as hex-encoded bytes.
    ///
    /// Capturing this now (even empty) ensures we have the field in
    /// all enrollment files when we later need it for quorum auditing.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attestation: Option<String>,

    // ── Quorum-ready fields (reserved for M-of-N) ───────────────
    /// Which Shamir share this device holds (0-indexed).
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub share_index: Option<u8>,

    /// Opaque quorum identifier linking all devices in a quorum group.
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quorum_id: Option<String>,

    /// M-of-N threshold for the quorum this device belongs to.
    /// `None` in the current 1:1 model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub threshold: Option<QuorumThreshold>,
}

/// M-of-N quorum threshold configuration.
///
/// Reserved for future multi-signing support. When implemented,
/// the Genesis secret will be split via Shamir Secret Sharing
/// across N devices, requiring M devices to reconstruct.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct QuorumThreshold {
    /// Minimum number of devices needed to reconstruct the secret.
    pub required: u8,
    /// Total number of shares (devices) in the quorum.
    pub total: u8,
}

/// Save enrollment metadata for a hardware wallet provider.
pub(crate) fn save_enrollment(metadata: &EnrollmentMetadata) -> Result<(), KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_enrollment.json", metadata.mode);
    let json = serde_json::to_string_pretty(metadata)
        .map_err(|e| KeyError::Serialization(e.to_string()))?;
    std::fs::write(dir.join(&filename), json)?;
    Ok(())
}

/// Load enrollment metadata for a hardware wallet provider.
pub(crate) fn load_enrollment(mode: &str) -> Result<EnrollmentMetadata, KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_enrollment.json", mode);
    let path = dir.join(&filename);
    if !path.exists() {
        return Err(KeyError::NotEnrolled(format!(
            "No enrollment data found for {}. Run the Genesis ceremony to enroll.",
            mode
        )));
    }
    let json = std::fs::read_to_string(&path)?;
    serde_json::from_str(&json).map_err(|e| {
        KeyError::EnrollmentCorrupted(format!("{} enrollment data is corrupted: {}", mode, e))
    })
}

// ---------------------------------------------------------------------------
// Encrypted secret file I/O
// ---------------------------------------------------------------------------

/// Save an encrypted Genesis secret blob for a hardware wallet provider.
///
/// The ciphertext is the output of `encrypt_secret()` — ChaCha20-Poly1305
/// authenticated ciphertext (48 bytes: 32 encrypted + 16 tag).
pub(crate) fn save_encrypted_secret(mode: &str, ciphertext: &[u8]) -> Result<(), KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    std::fs::write(dir.join(&filename), ciphertext)?;
    Ok(())
}

/// Load an encrypted Genesis secret blob for a hardware wallet provider.
pub(crate) fn load_encrypted_secret(mode: &str) -> Result<Vec<u8>, KeyError> {
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    let path = dir.join(&filename);
    if !path.exists() {
        return Err(KeyError::NotEnrolled(format!(
            "No encrypted secret found for {}. Run the Genesis ceremony first.",
            mode
        )));
    }
    let data = std::fs::read(&path)?;
    if data.is_empty() {
        return Err(KeyError::EnrollmentCorrupted(format!(
            "{} encrypted secret file is empty",
            mode
        )));
    }
    Ok(data)
}

// ---------------------------------------------------------------------------
// Provider rotation (rewrap)
// ---------------------------------------------------------------------------

/// Re-wrap the Genesis secret from one wrapping key to another.
///
/// This is the core primitive for provider rotation without re-genesis:
/// decrypt with the old device's key, re-encrypt with the new device's key,
/// and atomically replace the encrypted blob on disk.
///
/// The caller is responsible for:
/// 1. Deriving both wrapping keys (old and new) from their respective devices
/// 2. Updating the enrollment metadata to reflect the new device
/// 3. Signing a rotation record in the ceremony transcript
///
/// Returns the new ciphertext (already persisted to disk).
pub fn rewrap_secret(
    mode: &str,
    old_wrapping_key: &[u8; 32],
    new_wrapping_key: &[u8; 32],
) -> Result<Vec<u8>, KeyError> {
    // Load + decrypt with old key
    let old_blob = load_encrypted_secret(mode)?;
    let secret = decrypt_secret(&old_blob, old_wrapping_key)?;

    // Re-encrypt with new key (includes version prefix)
    let new_blob = encrypt_secret(&secret, new_wrapping_key)?;

    // Atomic-ish write: write to .tmp, then rename
    let dir = sovereignty_dir()?;
    let filename = format!("{}_genesis.encrypted", mode);
    let tmp_path = dir.join(format!("{}.tmp", filename));
    let final_path = dir.join(&filename);

    std::fs::write(&tmp_path, &new_blob)?;
    std::fs::rename(&tmp_path, &final_path)?;

    tracing::info!(
        mode = %mode,
        "Genesis secret re-wrapped with new wrapping key"
    );

    // Note: `secret` is [u8; 32] (Copy type) — it will be dropped when it
    // goes out of scope. For production hardening, consider using `zeroize`
    // crate with a `Zeroizing<[u8; 32]>` wrapper to guarantee scrubbing.

    Ok(new_blob)
}
