// crates/zp-keys/src/sovereignty/mod.rs
//
// Sovereignty Provider System — pluggable secret-gating for the Genesis key.
//
// The Genesis secret is always an Ed25519 key generated by ZeroPoint.
// The sovereignty provider controls HOW it's stored and WHO can unlock it.
// This separation means the key hierarchy works identically regardless of
// whether the secret is gated by Touch ID, a YubiKey, or a file on disk.
//
// Architecture:
//
//   SovereigntyProvider (trait)
//     ├── TouchIdProvider       macOS Secure Enclave, kSecAccessControlBiometryCurrentSet
//     ├── FingerprintProvider   Linux fprintd
//     ├── FaceEnrollProvider    Cross-platform webcam face enrollment (OpenCV)
//     ├── WindowsHelloProvider  Windows Hello (TPM 2.0 + biometric/PIN)
//     ├── YubiKeyProvider       FIDO2 hmac-secret or PIV Ed25519
//     ├── LedgerProvider        Ledger device key wrapping
//     ├── TrezorProvider        Trezor device key wrapping
//     ├── OnlyKeyProvider       OnlyKey challenge-response
//     ├── LoginPasswordProvider OS credential store (login password gate)
//     └── FileProvider          Disk file (headless / CI)

pub mod detection;
pub mod face;
pub mod file_based;
pub mod fingerprint;
pub mod hardware;
pub mod login_password;
pub mod touchid;
pub mod windows_hello;

use crate::error::KeyError;
use serde::{Deserialize, Serialize};

// Re-export BiometricEvidence from touchid module for use in transcripts
pub use touchid::BiometricEvidence;

// ---------------------------------------------------------------------------
// SovereigntyMode — the expanded enum
// ---------------------------------------------------------------------------

/// How the operator chose to protect their Genesis secret.
///
/// Each variant maps 1:1 to a `SovereigntyProvider` implementation.
/// Stored in `genesis.json` as the canonical record of how the root
/// of trust is gated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SovereigntyMode {
    // ── Biometric gates ──
    /// macOS Touch ID via Secure Enclave.
    /// The Keychain item has `kSecAccessControlBiometryCurrentSet` —
    /// every read requires a live fingerprint or Face ID scan.
    TouchId,

    /// Linux fingerprint reader via fprintd.
    /// Secret in Secret Service, gated by fprintd-verify on read.
    Fingerprint,

    /// Cross-platform face enrollment via webcam (OpenCV).
    /// A face template is captured during onboarding and verified
    /// against a live frame before unlocking the secret.
    FaceEnroll,

    /// Windows Hello — fingerprint, face, or PIN backed by TPM 2.0.
    /// Uses Windows Credential Manager with UserConsentVerifier gating.
    WindowsHello,

    // ── Hardware wallet gates ──
    /// YubiKey via FIDO2 hmac-secret or PIV challenge-response.
    /// The Genesis secret is encrypted to a device-derived key.
    YubiKey,

    /// Ledger hardware wallet.
    /// Genesis secret encrypted to a Ledger-derived wrapping key.
    Ledger,

    /// Trezor hardware wallet.
    /// Genesis secret encrypted to a Trezor-derived wrapping key.
    Trezor,

    /// OnlyKey hardware token.
    /// Genesis secret encrypted via OnlyKey challenge-response.
    OnlyKey,

    // ── Software gates ──
    /// OS credential store gated by the user's login password.
    /// Solid default — can upgrade to biometric or hardware wallet
    /// without re-keying.
    LoginPassword,

    /// File on disk. For headless servers, CI, or systems without
    /// a credential store. Weakest option — any process with user
    /// privileges can read the file.
    FileBased,

    // ── Legacy compat ──
    /// Legacy "biometric" mode from pre-0.2 genesis.json files.
    /// Resolves to TouchId on macOS, Fingerprint on Linux at runtime.
    #[serde(alias = "biometric")]
    LegacyBiometric,
}

impl SovereigntyMode {
    /// Resolve legacy modes to their concrete provider type.
    pub fn resolve(self) -> Self {
        match self {
            SovereigntyMode::LegacyBiometric => {
                if cfg!(target_os = "macos") {
                    SovereigntyMode::TouchId
                } else if cfg!(target_os = "linux") {
                    SovereigntyMode::Fingerprint
                } else if cfg!(target_os = "windows") {
                    SovereigntyMode::WindowsHello
                } else {
                    SovereigntyMode::LoginPassword
                }
            }
            other => other,
        }
    }

    /// Human-readable display name for the UI.
    pub fn display_name(&self) -> &'static str {
        match self {
            SovereigntyMode::TouchId => "Touch ID",
            SovereigntyMode::Fingerprint => "Fingerprint",
            SovereigntyMode::FaceEnroll => "Face Enrollment",
            SovereigntyMode::WindowsHello => "Windows Hello",
            SovereigntyMode::YubiKey => "YubiKey",
            SovereigntyMode::Ledger => "Ledger",
            SovereigntyMode::Trezor => "Trezor",
            SovereigntyMode::OnlyKey => "OnlyKey",
            SovereigntyMode::LoginPassword => "Login Password",
            SovereigntyMode::FileBased => "File on Disk",
            SovereigntyMode::LegacyBiometric => "Biometric (legacy)",
        }
    }

    /// Category for UI grouping.
    pub fn category(&self) -> SovereigntyCategory {
        match self {
            SovereigntyMode::TouchId
            | SovereigntyMode::Fingerprint
            | SovereigntyMode::FaceEnroll
            | SovereigntyMode::WindowsHello
            | SovereigntyMode::LegacyBiometric => SovereigntyCategory::Biometric,
            SovereigntyMode::YubiKey
            | SovereigntyMode::Ledger
            | SovereigntyMode::Trezor
            | SovereigntyMode::OnlyKey => SovereigntyCategory::HardwareWallet,
            SovereigntyMode::LoginPassword => SovereigntyCategory::Software,
            SovereigntyMode::FileBased => SovereigntyCategory::File,
        }
    }

    /// Whether this mode uses hardware that's built into the machine
    /// (biometrics, TPM). These don't need a "plug in" prompt.
    pub fn requires_hardware(&self) -> bool {
        matches!(
            self,
            SovereigntyMode::TouchId
                | SovereigntyMode::Fingerprint
                | SovereigntyMode::FaceEnroll
                | SovereigntyMode::WindowsHello
                | SovereigntyMode::YubiKey
                | SovereigntyMode::Ledger
                | SovereigntyMode::Trezor
                | SovereigntyMode::OnlyKey
        )
    }

    /// Whether this mode requires an external USB device to be connected.
    /// These modes get a "plug in your device" prompt during the Genesis ceremony.
    pub fn requires_external_device(&self) -> bool {
        matches!(
            self,
            SovereigntyMode::YubiKey
                | SovereigntyMode::Ledger
                | SovereigntyMode::Trezor
                | SovereigntyMode::OnlyKey
        )
    }
}

impl std::fmt::Display for SovereigntyMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Serialize name matches what goes into genesis.json
        match self {
            SovereigntyMode::TouchId => write!(f, "touch_id"),
            SovereigntyMode::Fingerprint => write!(f, "fingerprint"),
            SovereigntyMode::FaceEnroll => write!(f, "face_enroll"),
            SovereigntyMode::WindowsHello => write!(f, "windows_hello"),
            SovereigntyMode::YubiKey => write!(f, "yubi_key"),
            SovereigntyMode::Ledger => write!(f, "ledger"),
            SovereigntyMode::Trezor => write!(f, "trezor"),
            SovereigntyMode::OnlyKey => write!(f, "only_key"),
            SovereigntyMode::LoginPassword => write!(f, "login_password"),
            SovereigntyMode::FileBased => write!(f, "file_based"),
            SovereigntyMode::LegacyBiometric => write!(f, "biometric"),
        }
    }
}

impl SovereigntyMode {
    /// Auto-detect the best available sovereignty provider for this platform.
    ///
    /// Priority: biometric (platform-native) > OS credential store > file fallback.
    /// This is the Tier A quick-start path — no questions asked.
    pub fn auto_detect() -> Self {
        #[cfg(target_os = "macos")]
        {
            // Touch ID is available on all modern Macs (T2 chip or Apple Silicon).
            // `security` command presence is a reliable proxy.
            if std::process::Command::new("security")
                .arg("list-keychains")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
            {
                return SovereigntyMode::TouchId;
            }
            return SovereigntyMode::LoginPassword;
        }

        #[cfg(target_os = "windows")]
        {
            return SovereigntyMode::WindowsHello;
        }

        #[cfg(target_os = "linux")]
        {
            // Check for Secret Service (gnome-keyring / KWallet)
            let has_secret_service = std::process::Command::new("dbus-send")
                .args([
                    "--session",
                    "--dest=org.freedesktop.secrets",
                    "--print-reply",
                    "/org/freedesktop/secrets",
                    "org.freedesktop.DBus.Peer.Ping",
                ])
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false);

            if has_secret_service {
                return SovereigntyMode::LoginPassword;
            }

            // No credential store — file fallback (headless server scenario)
            return SovereigntyMode::FileBased;
        }

        #[allow(unreachable_code)]
        SovereigntyMode::LoginPassword
    }
}

impl Default for SovereigntyMode {
    fn default() -> Self {
        SovereigntyMode::auto_detect()
    }
}

/// Category grouping for UI display.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SovereigntyCategory {
    Biometric,
    HardwareWallet,
    Software,
    File,
}

/// Implementation readiness of a sovereignty provider.
/// The ceremony and UI use this to determine what can actually be offered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderStatus {
    /// Fully implemented — save, load, enroll all work.
    Ready,
    /// Detection works, but save/load/enroll are not yet implemented.
    /// The UI should show this provider as "coming soon" and not offer it.
    DetectionOnly,
    /// Partially implemented — some operations work, some don't.
    /// The UI should show this with caveats.
    Partial,
}

impl SovereigntyMode {
    /// Whether this provider's cryptographic operations are fully implemented.
    /// The ceremony MUST NOT offer a provider whose status is `DetectionOnly`.
    pub fn implementation_status(&self) -> ProviderStatus {
        match self {
            // Fully working
            SovereigntyMode::TouchId => ProviderStatus::Ready,
            SovereigntyMode::Fingerprint => ProviderStatus::Ready,
            SovereigntyMode::LoginPassword => ProviderStatus::Ready,
            SovereigntyMode::FileBased => ProviderStatus::Ready,
            // Partial: detection + biometric check works, but not OS-level gating
            SovereigntyMode::FaceEnroll => ProviderStatus::Partial,
            SovereigntyMode::WindowsHello => ProviderStatus::Partial,
            // Detection only: no save/load/enroll
            SovereigntyMode::YubiKey => ProviderStatus::DetectionOnly,
            SovereigntyMode::Ledger => ProviderStatus::DetectionOnly,
            SovereigntyMode::Trezor => {
                if cfg!(feature = "hw-trezor") {
                    ProviderStatus::Ready
                } else {
                    ProviderStatus::DetectionOnly
                }
            }
            SovereigntyMode::OnlyKey => ProviderStatus::DetectionOnly,
            // Legacy
            SovereigntyMode::LegacyBiometric => ProviderStatus::Ready,
        }
    }

    /// Whether this provider can actually complete a Genesis ceremony right now.
    pub fn is_ceremony_ready(&self) -> bool {
        self.implementation_status() != ProviderStatus::DetectionOnly
    }
}

// ---------------------------------------------------------------------------
// SovereigntyProvider trait
// ---------------------------------------------------------------------------

/// Result of hardware/capability detection for a sovereignty mode.
#[derive(Debug, Clone, Serialize)]
pub struct ProviderCapability {
    /// The sovereignty mode this capability is for.
    pub mode: SovereigntyMode,
    /// Whether the hardware/software is available on this system.
    pub available: bool,
    /// Human-readable description of what was detected.
    pub description: String,
    /// Whether enrollment is needed before first use.
    pub requires_enrollment: bool,
    /// Optional detail (e.g., device serial, firmware version).
    pub detail: Option<String>,
    /// Whether the provider is fully implemented and can complete a Genesis ceremony.
    pub implementation_status: ProviderStatus,
}

/// Result of an enrollment operation (e.g., face capture, hardware wallet pairing).
#[derive(Debug)]
pub struct EnrollmentResult {
    /// Opaque enrollment data to persist (e.g., face template hash, device ID).
    /// Stored in `~/.zeropoint/sovereignty/enrollment.json`.
    pub enrollment_data: Vec<u8>,
    /// Human-readable summary for the terminal.
    pub summary: String,
}

// ---------------------------------------------------------------------------
// Provider capabilities — what a provider can do beyond the base trait
// ---------------------------------------------------------------------------

/// Capability flags for a sovereignty provider.
///
/// This enables the ceremony, governance, and UI layers to negotiate
/// what operations are available for a given provider *without* probing
/// for errors. For example, the UI can show a "Rotate" button only if
/// the provider advertises `CAN_REWRAP`.
///
/// Implemented as a bitflag-style struct for efficient combining and
/// testing, while remaining serde-friendly for the WS protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ProviderCapabilities(u32);

impl ProviderCapabilities {
    /// Basic save/load/verify operations.
    pub const BASE: Self = Self(0);
    /// Provider supports device attestation during enrollment.
    pub const CAN_ATTEST: Self = Self(1 << 0);
    /// Provider supports re-wrapping (rotation) without re-genesis.
    pub const CAN_REWRAP: Self = Self(1 << 1);
    /// Provider supports passphrase-protected wallets.
    pub const CAN_PASSPHRASE: Self = Self(1 << 2);
    /// Provider can participate in M-of-N quorum signing.
    pub const CAN_QUORUM: Self = Self(1 << 3);
    /// Provider supports timestamped/salted key derivation for key rotation.
    pub const CAN_SALTED_DERIVATION: Self = Self(1 << 4);
    /// Provider has non-volatile enrollment (enrollment data persists on device).
    pub const HAS_DEVICE_STORAGE: Self = Self(1 << 5);
    /// Provider supports post-genesis upgrade (re-gating existing secret).
    pub const CAN_UPGRADE: Self = Self(1 << 6);
    /// Provider produces biometric evidence for transcripts.
    pub const HAS_BIOMETRIC_EVIDENCE: Self = Self(1 << 7);

    /// Combine two capability sets.
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Test whether a specific capability is present.
    pub const fn has(self, cap: Self) -> bool {
        (self.0 & cap.0) == cap.0
    }

    /// Raw value for serialization.
    pub const fn bits(self) -> u32 {
        self.0
    }

    /// Construct from raw bits.
    pub const fn from_bits(bits: u32) -> Self {
        Self(bits)
    }
}

impl Serialize for ProviderCapabilities {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // Serialize as a list of named capabilities for human-readable formats
        let mut names = Vec::new();
        if self.has(Self::CAN_ATTEST) {
            names.push("can_attest");
        }
        if self.has(Self::CAN_REWRAP) {
            names.push("can_rewrap");
        }
        if self.has(Self::CAN_PASSPHRASE) {
            names.push("can_passphrase");
        }
        if self.has(Self::CAN_QUORUM) {
            names.push("can_quorum");
        }
        if self.has(Self::CAN_SALTED_DERIVATION) {
            names.push("can_salted_derivation");
        }
        if self.has(Self::HAS_DEVICE_STORAGE) {
            names.push("has_device_storage");
        }
        if self.has(Self::CAN_UPGRADE) {
            names.push("can_upgrade");
        }
        if self.has(Self::HAS_BIOMETRIC_EVIDENCE) {
            names.push("has_biometric_evidence");
        }
        names.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ProviderCapabilities {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let names: Vec<String> = Vec::deserialize(deserializer)?;
        let mut caps = Self::BASE;
        for name in &names {
            match name.as_str() {
                "can_attest" => caps = caps.union(Self::CAN_ATTEST),
                "can_rewrap" => caps = caps.union(Self::CAN_REWRAP),
                "can_passphrase" => caps = caps.union(Self::CAN_PASSPHRASE),
                "can_quorum" => caps = caps.union(Self::CAN_QUORUM),
                "can_salted_derivation" => caps = caps.union(Self::CAN_SALTED_DERIVATION),
                "has_device_storage" => caps = caps.union(Self::HAS_DEVICE_STORAGE),
                "can_upgrade" => caps = caps.union(Self::CAN_UPGRADE),
                "has_biometric_evidence" => caps = caps.union(Self::HAS_BIOMETRIC_EVIDENCE),
                _ => {} // Ignore unknown capabilities (forward compat)
            }
        }
        Ok(caps)
    }
}

/// The core trait every sovereignty provider must implement.
///
/// The Genesis secret is always a 32-byte Ed25519 seed generated by ZeroPoint.
/// The provider controls how it's stored, how it's unlocked, and what physical
/// proof of presence is required.
pub trait SovereigntyProvider: Send + Sync {
    /// Which sovereignty mode this provider handles.
    fn mode(&self) -> SovereigntyMode;

    /// Detect whether this provider's hardware/software is available.
    fn detect(&self) -> ProviderCapability;

    /// Store the Genesis secret with this provider's gating mechanism.
    ///
    /// For biometrics: stores in OS credential store with biometric access control.
    /// For hardware wallets: encrypts the secret to a device-derived wrapping key.
    /// For login password: stores in OS credential store with default access.
    /// For file-based: writes to disk.
    fn save_secret(&self, secret: &[u8; 32]) -> Result<(), KeyError>;

    /// Load the Genesis secret, requiring the provider's proof of presence.
    ///
    /// For biometrics: triggers biometric scan before unlocking.
    /// For hardware wallets: requires device to be plugged in and confirmed.
    /// For login password: OS may prompt for login password.
    /// For file-based: reads from disk (no verification).
    fn load_secret(&self) -> Result<[u8; 32], KeyError>;

    /// Verify physical presence without loading the secret.
    ///
    /// Used for ongoing operations where the secret is already cached
    /// but we want to re-confirm the operator is present.
    fn verify_presence(&self) -> Result<(), KeyError>;

    /// Perform enrollment if this provider requires it.
    ///
    /// For face enrollment: captures webcam frames, builds template.
    /// For hardware wallets: pairs with device, derives wrapping key.
    /// For biometrics/password: may be a no-op (OS handles enrollment).
    fn enroll(&self) -> Result<Option<EnrollmentResult>, KeyError> {
        Ok(None) // Default: no enrollment needed
    }

    /// Advertise this provider's capabilities beyond the base trait.
    ///
    /// The ceremony, governance proxy, and UI use this to decide what
    /// operations to offer (rotation, quorum enrollment, etc.) without
    /// probing for errors or checking feature flags externally.
    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities::BASE // Default: base operations only
    }

    /// Collect biometric evidence for the genesis transcript (v0.2).
    ///
    /// Returns cryptographic proof that a biometric verification occurred:
    /// a nonce-challenge-response binding the verification to a specific
    /// point in time, preventing replay.
    ///
    /// Only biometric providers return evidence. Hardware wallets and
    /// software gates return None.
    fn biometric_evidence(&self) -> Option<touchid::BiometricEvidence> {
        None // Default: no biometric evidence
    }

    /// Upgrade: re-gate an existing Genesis secret under this provider.
    ///
    /// This enables post-genesis sovereignty upgrades:
    ///   login_password → touch_id
    ///   touch_id → face_enroll (add secondary biometric)
    ///   login_password → yubikey
    ///
    /// The caller loads the secret from the OLD provider and passes it
    /// here. This provider enrolls (if needed) and saves the secret
    /// under its own gating mechanism. The old provider's entry is NOT
    /// deleted — that's the caller's responsibility after confirming
    /// the new entry works.
    ///
    /// Returns the enrollment result (if any) for transcript recording.
    fn upgrade_from(&self, secret: &[u8; 32]) -> Result<Option<EnrollmentResult>, KeyError> {
        // Default: enroll + save. Providers can override for custom flows.
        if self.detect().requires_enrollment {
            self.enroll()?;
        }
        self.save_secret(secret)?;
        Ok(None)
    }

    /// Human-readable name for the provider.
    fn display_name(&self) -> &'static str {
        self.mode().display_name()
    }
}

// ---------------------------------------------------------------------------
// Provider registry — detect all available providers
// ---------------------------------------------------------------------------

/// Scan the system and return capabilities for all known sovereignty providers.
pub fn detect_all_providers() -> Vec<ProviderCapability> {
    vec![
        // Biometric providers
        touchid::TouchIdProvider.detect(),
        fingerprint::FingerprintProvider.detect(),
        face::FaceEnrollProvider.detect(),
        windows_hello::WindowsHelloProvider.detect(),
        // Hardware wallet providers
        hardware::yubikey::YubiKeyProvider.detect(),
        hardware::ledger::LedgerProvider.detect(),
        hardware::trezor::TrezorProvider.detect(),
        hardware::onlykey::OnlyKeyProvider.detect(),
        // Software providers (always available)
        login_password::LoginPasswordProvider.detect(),
        file_based::FileProvider.detect(),
    ]
}

/// Get the appropriate provider for a given sovereignty mode.
pub fn provider_for(mode: SovereigntyMode) -> Box<dyn SovereigntyProvider> {
    let mode = mode.resolve();
    match mode {
        SovereigntyMode::TouchId => Box::new(touchid::TouchIdProvider),
        SovereigntyMode::Fingerprint => Box::new(fingerprint::FingerprintProvider),
        SovereigntyMode::FaceEnroll => Box::new(face::FaceEnrollProvider),
        SovereigntyMode::WindowsHello => Box::new(windows_hello::WindowsHelloProvider),
        SovereigntyMode::YubiKey => Box::new(hardware::yubikey::YubiKeyProvider),
        SovereigntyMode::Ledger => Box::new(hardware::ledger::LedgerProvider),
        SovereigntyMode::Trezor => Box::new(hardware::trezor::TrezorProvider),
        SovereigntyMode::OnlyKey => Box::new(hardware::onlykey::OnlyKeyProvider),
        SovereigntyMode::LoginPassword => Box::new(login_password::LoginPasswordProvider),
        SovereigntyMode::FileBased => Box::new(file_based::FileProvider),
        SovereigntyMode::LegacyBiometric => {
            // Should have been resolved above, but handle gracefully
            Box::new(login_password::LoginPasswordProvider)
        }
    }
}

// ---------------------------------------------------------------------------
// Parsing from onboarding strings
// ---------------------------------------------------------------------------

impl SovereigntyMode {
    /// Parse from the string the onboarding UI sends.
    /// Handles both new specific modes and legacy strings.
    pub fn from_onboard_str(s: &str) -> Self {
        match s {
            "touch_id" | "touchid" | "touch-id" => SovereigntyMode::TouchId,
            "fingerprint" | "fprintd" => SovereigntyMode::Fingerprint,
            "face_enroll" | "face-enroll" | "face" | "camera" => SovereigntyMode::FaceEnroll,
            "windows_hello" | "windows-hello" | "windowshello" | "hello" => {
                SovereigntyMode::WindowsHello
            }
            "yubikey" | "yubi_key" | "yubi-key" => SovereigntyMode::YubiKey,
            "ledger" => SovereigntyMode::Ledger,
            "trezor" => SovereigntyMode::Trezor,
            "onlykey" | "only_key" | "only-key" => SovereigntyMode::OnlyKey,
            "login-password" | "login_password" | "login" | "password" => {
                SovereigntyMode::LoginPassword
            }
            "file-based" | "file_based" | "file" => SovereigntyMode::FileBased,
            // Legacy: "biometric" or "bio" resolves at runtime
            "biometric" | "bio" => SovereigntyMode::LegacyBiometric,
            // Auto-detect: pick the best available
            _ => SovereigntyMode::LoginPassword,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sovereignty_mode_display() {
        assert_eq!(SovereigntyMode::TouchId.to_string(), "touch_id");
        assert_eq!(SovereigntyMode::YubiKey.to_string(), "yubi_key");
        assert_eq!(SovereigntyMode::LoginPassword.to_string(), "login_password");
        assert_eq!(SovereigntyMode::FileBased.to_string(), "file_based");
    }

    #[test]
    fn test_sovereignty_mode_serde_roundtrip() {
        let mode = SovereigntyMode::TouchId;
        let json = serde_json::to_string(&mode).unwrap();
        assert_eq!(json, "\"touch_id\"");
        let parsed: SovereigntyMode = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, mode);
    }

    #[test]
    fn test_legacy_biometric_deserializes() {
        let parsed: SovereigntyMode = serde_json::from_str("\"biometric\"").unwrap();
        assert_eq!(parsed, SovereigntyMode::LegacyBiometric);
    }

    #[test]
    fn test_from_onboard_str() {
        assert_eq!(
            SovereigntyMode::from_onboard_str("touch-id"),
            SovereigntyMode::TouchId
        );
        assert_eq!(
            SovereigntyMode::from_onboard_str("yubikey"),
            SovereigntyMode::YubiKey
        );
        assert_eq!(
            SovereigntyMode::from_onboard_str("biometric"),
            SovereigntyMode::LegacyBiometric
        );
    }

    #[test]
    fn test_detect_all_providers_does_not_panic() {
        let caps = detect_all_providers();
        assert!(caps.len() >= 2); // At least login_password + file_based
    }

    // ── v0.2 biometric tests ─────────────────────────────────────

    #[test]
    fn test_biometric_evidence_structure() {
        let evidence = BiometricEvidence {
            method: "touchid".into(),
            verified_at: "2026-04-17T12:00:00Z".into(),
            challenge_nonce: "aa".repeat(32),
            challenge_response: "bb".repeat(32),
            os_enforced: true,
            hardware_attestation: String::new(),
        };

        let json = serde_json::to_value(&evidence).unwrap();
        assert_eq!(json["method"], "touchid");
        assert_eq!(json["os_enforced"], true);
        assert!(json["challenge_nonce"].as_str().unwrap().len() == 64);
        assert!(json["challenge_response"].as_str().unwrap().len() == 64);
    }

    #[test]
    fn test_biometric_evidence_in_transcript_json() {
        // Verify that biometric evidence serializes correctly for inclusion
        // in genesis transcripts
        let evidence = BiometricEvidence {
            method: "faceid".into(),
            verified_at: chrono::Utc::now().to_rfc3339(),
            challenge_nonce: hex::encode([0xaa; 32]),
            challenge_response: hex::encode([0xbb; 32]),
            os_enforced: false,
            hardware_attestation: String::new(),
        };

        let transcript = serde_json::json!({
            "ceremony": "genesis",
            "biometric_evidence": evidence,
        });

        let evidence_obj = &transcript["biometric_evidence"];
        assert_eq!(evidence_obj["method"], "faceid");
        assert_eq!(evidence_obj["os_enforced"], false);
    }

    #[test]
    fn test_provider_capabilities_upgrade_flag() {
        let caps = ProviderCapabilities::BASE
            .union(ProviderCapabilities::CAN_UPGRADE)
            .union(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE);

        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
        assert!(!caps.has(ProviderCapabilities::CAN_ATTEST));
    }

    #[test]
    fn test_provider_capabilities_serde_roundtrip() {
        let caps = ProviderCapabilities::CAN_UPGRADE
            .union(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE);

        let json = serde_json::to_string(&caps).unwrap();
        assert!(json.contains("can_upgrade"));
        assert!(json.contains("has_biometric_evidence"));

        let parsed: ProviderCapabilities = serde_json::from_str(&json).unwrap();
        assert!(parsed.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(parsed.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_touchid_provider_has_upgrade_capability() {
        let provider = touchid::TouchIdProvider;
        let caps = provider.capabilities();
        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_face_provider_has_upgrade_capability() {
        let provider = face::FaceEnrollProvider;
        let caps = provider.capabilities();
        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
    }

    #[test]
    fn test_login_password_default_capabilities() {
        let provider = login_password::LoginPasswordProvider;
        let caps = provider.capabilities();
        // Login password has no special capabilities
        assert!(!caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(!caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_sovereignty_upgrade_same_mode_noop() {
        // Upgrading to the same mode should be detected by the handler
        // (not tested here — that's a server-layer test)
        // But we verify the provider trait has upgrade_from
        let provider = touchid::TouchIdProvider;
        assert_eq!(provider.mode(), SovereigntyMode::TouchId);
    }
}
