// crates/zp-keys/src/sovereignty/mod.rs
//
// Sovereignty Provider System — pluggable secret-gating for the Genesis key.
//
// The Genesis secret is always an Ed25519 key generated by ZeroPoint.
// The sovereignty provider controls HOW it's stored and WHO can unlock it.
// This separation means the key hierarchy works identically regardless of
// whether the secret is gated by Touch ID, a YubiKey, or a file on disk.
//
// Architecture:
//
//   SovereigntyProvider (trait)
//     ├── TouchIdProvider       macOS Secure Enclave, kSecAccessControlBiometryCurrentSet
//     ├── FingerprintProvider   Linux fprintd
//     ├── FaceEnrollProvider    Cross-platform webcam face enrollment (OpenCV)
//     ├── WindowsHelloProvider  Windows Hello (TPM 2.0 + biometric/PIN)
//     ├── YubiKeyProvider       FIDO2 hmac-secret or PIV Ed25519
//     ├── LedgerProvider        Ledger device key wrapping
//     ├── TrezorProvider        Trezor device key wrapping
//     ├── OnlyKeyProvider       OnlyKey challenge-response
//     ├── LoginPasswordProvider OS credential store (login password gate)
//     └── FileProvider          Disk file (headless / CI)
//
// Blast radius — surfaces that must update together when a sovereignty
// provider is added, renamed, or has its status changed:
//   biometric.rs                       (legacy shim, re-exports)
//   lib.rs                             (top-level re-exports)
//   onboard/genesis.rs                 (Genesis ceremony)
//   onboard/detect.rs                  (provider scan)
//   onboard/state.rs                   (step machine)
//   onboard.html                       (sovereignty cards)
//   onboard.js                         (updatePlatformUI, selectSovereignty,
//                                       showGenesisComplete, summary labels)
//   narration/onboard/scripts.md       (narration mentions biometrics)
//   dashboard.html                     (sovereignty badge display)
//   security.rs                        (posture check)
//
// Feature flags (in `zp-keys/Cargo.toml`):
//   os-keychain, face-enroll, hw-yubikey, hw-ledger, hw-trezor, hw-onlykey
//
// Design direction for M-of-N quorum sovereignty: see
// `docs/design/quorum-sovereignty.md`.

pub mod detection;
pub mod face;
pub mod file_based;
pub mod fingerprint;
pub mod hardware;
pub mod login_password;
pub mod touchid;
pub mod windows_hello;

use crate::error::KeyError;
use serde::{Deserialize, Serialize};

// Re-export BiometricEvidence from touchid module for use in transcripts
pub use touchid::BiometricEvidence;

// ---------------------------------------------------------------------------
// SovereigntyMode — the expanded enum
// ---------------------------------------------------------------------------

/// How the operator chose to protect their Genesis secret.
///
/// Each variant maps 1:1 to a `SovereigntyProvider` implementation.
/// Stored in `genesis.json` as the canonical record of how the root
/// of trust is gated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SovereigntyMode {
    // ── Biometric gates ──
    /// macOS Touch ID via Secure Enclave.
    /// The Keychain item has `kSecAccessControlBiometryCurrentSet` —
    /// every read requires a live fingerprint or Face ID scan.
    TouchId,

    /// Linux fingerprint reader via fprintd.
    /// Secret in Secret Service, gated by fprintd-verify on read.
    Fingerprint,

    /// Cross-platform face enrollment via webcam (OpenCV).
    /// A face template is captured during onboarding and verified
    /// against a live frame before unlocking the secret.
    FaceEnroll,

    /// Windows Hello — fingerprint, face, or PIN backed by TPM 2.0.
    /// Uses Windows Credential Manager with UserConsentVerifier gating.
    WindowsHello,

    // ── Hardware wallet gates ──
    /// YubiKey via FIDO2 hmac-secret or PIV challenge-response.
    /// The Genesis secret is encrypted to a device-derived key.
    YubiKey,

    /// Ledger hardware wallet.
    /// Genesis secret encrypted to a Ledger-derived wrapping key.
    Ledger,

    /// Trezor hardware wallet.
    /// Genesis secret encrypted to a Trezor-derived wrapping key.
    Trezor,

    /// OnlyKey hardware token.
    /// Genesis secret encrypted via OnlyKey challenge-response.
    OnlyKey,

    // ── Software gates ──
    /// OS credential store gated by the user's login password.
    /// Solid default — can upgrade to biometric or hardware wallet
    /// without re-keying.
    LoginPassword,

    /// File on disk. For headless servers, CI, or systems without
    /// a credential store. Weakest option — any process with user
    /// privileges can read the file.
    FileBased,

    // ── Legacy compat ──
    /// Legacy "biometric" mode from pre-0.2 genesis.json files.
    /// Resolves to TouchId on macOS, Fingerprint on Linux at runtime.
    #[serde(alias = "biometric")]
    LegacyBiometric,
}

impl SovereigntyMode {
    /// Resolve legacy modes to their concrete provider type.
    pub fn resolve(self) -> Self {
        match self {
            SovereigntyMode::LegacyBiometric => {
                if cfg!(target_os = "macos") {
                    SovereigntyMode::TouchId
                } else if cfg!(target_os = "linux") {
                    SovereigntyMode::Fingerprint
                } else if cfg!(target_os = "windows") {
                    SovereigntyMode::WindowsHello
                } else {
                    SovereigntyMode::LoginPassword
                }
            }
            other => other,
        }
    }

    /// Human-readable display name for the UI.
    pub fn display_name(&self) -> &'static str {
        match self {
            SovereigntyMode::TouchId => "Touch ID",
            SovereigntyMode::Fingerprint => "Fingerprint",
            SovereigntyMode::FaceEnroll => "Face Enrollment",
            SovereigntyMode::WindowsHello => "Windows Hello",
            SovereigntyMode::YubiKey => "YubiKey",
            SovereigntyMode::Ledger => "Ledger",
            SovereigntyMode::Trezor => "Trezor",
            SovereigntyMode::OnlyKey => "OnlyKey",
            SovereigntyMode::LoginPassword => "Login Password",
            SovereigntyMode::FileBased => "File on Disk",
            SovereigntyMode::LegacyBiometric => "Biometric (legacy)",
        }
    }

    /// Category for UI grouping.
    pub fn category(&self) -> SovereigntyCategory {
        match self {
            SovereigntyMode::TouchId
            | SovereigntyMode::Fingerprint
            | SovereigntyMode::FaceEnroll
            | SovereigntyMode::WindowsHello
            | SovereigntyMode::LegacyBiometric => SovereigntyCategory::Biometric,
            SovereigntyMode::YubiKey
            | SovereigntyMode::Ledger
            | SovereigntyMode::Trezor
            | SovereigntyMode::OnlyKey => SovereigntyCategory::HardwareWallet,
            SovereigntyMode::LoginPassword => SovereigntyCategory::Software,
            SovereigntyMode::FileBased => SovereigntyCategory::File,
        }
    }

    /// Whether this mode uses hardware that's built into the machine
    /// (biometrics, TPM). These don't need a "plug in" prompt.
    pub fn requires_hardware(&self) -> bool {
        matches!(
            self,
            SovereigntyMode::TouchId
                | SovereigntyMode::Fingerprint
                | SovereigntyMode::FaceEnroll
                | SovereigntyMode::WindowsHello
                | SovereigntyMode::YubiKey
                | SovereigntyMode::Ledger
                | SovereigntyMode::Trezor
                | SovereigntyMode::OnlyKey
        )
    }

    /// Whether this mode requires an external USB device to be connected.
    /// These modes get a "plug in your device" prompt during the Genesis ceremony.
    pub fn requires_external_device(&self) -> bool {
        matches!(
            self,
            SovereigntyMode::YubiKey
                | SovereigntyMode::Ledger
                | SovereigntyMode::Trezor
                | SovereigntyMode::OnlyKey
        )
    }
}

impl std::fmt::Display for SovereigntyMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Serialize name matches what goes into genesis.json
        match self {
            SovereigntyMode::TouchId => write!(f, "touch_id"),
            SovereigntyMode::Fingerprint => write!(f, "fingerprint"),
            SovereigntyMode::FaceEnroll => write!(f, "face_enroll"),
            SovereigntyMode::WindowsHello => write!(f, "windows_hello"),
            SovereigntyMode::YubiKey => write!(f, "yubi_key"),
            SovereigntyMode::Ledger => write!(f, "ledger"),
            SovereigntyMode::Trezor => write!(f, "trezor"),
            SovereigntyMode::OnlyKey => write!(f, "only_key"),
            SovereigntyMode::LoginPassword => write!(f, "login_password"),
            SovereigntyMode::FileBased => write!(f, "file_based"),
            SovereigntyMode::LegacyBiometric => write!(f, "biometric"),
        }
    }
}

impl SovereigntyMode {
    /// Auto-detect the best available sovereignty provider for this platform.
    ///
    /// Priority: biometric (platform-native) > OS credential store > file fallback.
    /// This is the Tier A quick-start path — no questions asked.
    pub fn auto_detect() -> Self {
        #[cfg(target_os = "macos")]
        {
            // Touch ID is available on all modern Macs (T2 chip or Apple Silicon).
            // `security` command presence is a reliable proxy.
            if std::process::Command::new("security")
                .arg("list-keychains")
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false)
            {
                return SovereigntyMode::TouchId;
            }
            return SovereigntyMode::LoginPassword;
        }

        #[cfg(target_os = "windows")]
        {
            return SovereigntyMode::WindowsHello;
        }

        #[cfg(target_os = "linux")]
        {
            // Check for Secret Service (gnome-keyring / KWallet)
            let has_secret_service = std::process::Command::new("dbus-send")
                .args([
                    "--session",
                    "--dest=org.freedesktop.secrets",
                    "--print-reply",
                    "/org/freedesktop/secrets",
                    "org.freedesktop.DBus.Peer.Ping",
                ])
                .output()
                .map(|o| o.status.success())
                .unwrap_or(false);

            if has_secret_service {
                return SovereigntyMode::LoginPassword;
            }

            // No credential store — file fallback (headless server scenario)
            return SovereigntyMode::FileBased;
        }

        #[allow(unreachable_code)]
        SovereigntyMode::LoginPassword
    }
}

impl Default for SovereigntyMode {
    fn default() -> Self {
        SovereigntyMode::auto_detect()
    }
}

/// Category grouping for UI display.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SovereigntyCategory {
    Biometric,
    HardwareWallet,
    Software,
    File,
}

/// Implementation readiness of a sovereignty provider.
/// The ceremony and UI use this to determine what can actually be offered.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ProviderStatus {
    /// Fully implemented — save, load, enroll all work.
    Ready,
    /// Detection works, but save/load/enroll are not yet implemented.
    /// The UI should show this provider as "coming soon" and not offer it.
    DetectionOnly,
    /// Partially implemented — some operations work, some don't.
    /// The UI should show this with caveats.
    Partial,
}

impl SovereigntyMode {
    /// Whether this provider's cryptographic operations are fully implemented.
    /// The ceremony MUST NOT offer a provider whose status is `DetectionOnly`.
    pub fn implementation_status(&self) -> ProviderStatus {
        match self {
            // Fully working
            SovereigntyMode::TouchId => ProviderStatus::Ready,
            SovereigntyMode::Fingerprint => ProviderStatus::Ready,
            SovereigntyMode::LoginPassword => ProviderStatus::Ready,
            SovereigntyMode::FileBased => ProviderStatus::Ready,
            // Partial: detection + biometric check works, but not OS-level gating
            SovereigntyMode::FaceEnroll => ProviderStatus::Partial,
            SovereigntyMode::WindowsHello => ProviderStatus::Partial,
            // Detection only: no save/load/enroll
            SovereigntyMode::YubiKey => ProviderStatus::DetectionOnly,
            SovereigntyMode::Ledger => ProviderStatus::DetectionOnly,
            SovereigntyMode::Trezor => {
                if cfg!(feature = "hw-trezor") {
                    ProviderStatus::Ready
                } else {
                    ProviderStatus::DetectionOnly
                }
            }
            SovereigntyMode::OnlyKey => ProviderStatus::DetectionOnly,
            // Legacy
            SovereigntyMode::LegacyBiometric => ProviderStatus::Ready,
        }
    }

    /// Whether this provider can actually complete a Genesis ceremony right now.
    pub fn is_ceremony_ready(&self) -> bool {
        self.implementation_status() != ProviderStatus::DetectionOnly
    }
}

// ---------------------------------------------------------------------------
// SovereigntyProvider trait
// ---------------------------------------------------------------------------

/// Result of hardware/capability detection for a sovereignty mode.
#[derive(Debug, Clone, Serialize)]
pub struct ProviderCapability {
    /// The sovereignty mode this capability is for.
    pub mode: SovereigntyMode,
    /// Whether the hardware/software is available on this system.
    pub available: bool,
    /// Human-readable description of what was detected.
    pub description: String,
    /// Whether enrollment is needed before first use.
    pub requires_enrollment: bool,
    /// Optional detail (e.g., device serial, firmware version).
    pub detail: Option<String>,
    /// Whether the provider is fully implemented and can complete a Genesis ceremony.
    pub implementation_status: ProviderStatus,
}

/// Result of an enrollment operation (e.g., face capture, hardware wallet pairing).
#[derive(Debug)]
pub struct EnrollmentResult {
    /// Opaque enrollment data to persist (e.g., face template hash, device ID).
    /// Stored in `~/ZeroPoint/sovereignty/enrollment.json`.
    pub enrollment_data: Vec<u8>,
    /// Human-readable summary for the terminal.
    pub summary: String,
}

// ---------------------------------------------------------------------------
// Provider capabilities — what a provider can do beyond the base trait
// ---------------------------------------------------------------------------

/// Capability flags for a sovereignty provider.
///
/// This enables the ceremony, governance, and UI layers to negotiate
/// what operations are available for a given provider *without* probing
/// for errors. For example, the UI can show a "Rotate" button only if
/// the provider advertises `CAN_REWRAP`.
///
/// Implemented as a bitflag-style struct for efficient combining and
/// testing, while remaining serde-friendly for the WS protocol.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ProviderCapabilities(u32);

impl ProviderCapabilities {
    /// Basic save/load/verify operations.
    pub const BASE: Self = Self(0);
    /// Provider supports device attestation during enrollment.
    pub const CAN_ATTEST: Self = Self(1 << 0);
    /// Provider supports re-wrapping (rotation) without re-genesis.
    pub const CAN_REWRAP: Self = Self(1 << 1);
    /// Provider supports passphrase-protected wallets.
    pub const CAN_PASSPHRASE: Self = Self(1 << 2);
    /// Provider can participate in M-of-N quorum signing.
    pub const CAN_QUORUM: Self = Self(1 << 3);
    /// Provider supports timestamped/salted key derivation for key rotation.
    pub const CAN_SALTED_DERIVATION: Self = Self(1 << 4);
    /// Provider has non-volatile enrollment (enrollment data persists on device).
    pub const HAS_DEVICE_STORAGE: Self = Self(1 << 5);
    /// Provider supports post-genesis upgrade (re-gating existing secret).
    pub const CAN_UPGRADE: Self = Self(1 << 6);
    /// Provider produces biometric evidence for transcripts.
    pub const HAS_BIOMETRIC_EVIDENCE: Self = Self(1 << 7);

    /// Combine two capability sets.
    pub const fn union(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    /// Test whether a specific capability is present.
    pub const fn has(self, cap: Self) -> bool {
        (self.0 & cap.0) == cap.0
    }

    /// Raw value for serialization.
    pub const fn bits(self) -> u32 {
        self.0
    }

    /// Construct from raw bits.
    pub const fn from_bits(bits: u32) -> Self {
        Self(bits)
    }
}

impl Serialize for ProviderCapabilities {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // Serialize as a list of named capabilities for human-readable formats
        let mut names = Vec::new();
        if self.has(Self::CAN_ATTEST) {
            names.push("can_attest");
        }
        if self.has(Self::CAN_REWRAP) {
            names.push("can_rewrap");
        }
        if self.has(Self::CAN_PASSPHRASE) {
            names.push("can_passphrase");
        }
        if self.has(Self::CAN_QUORUM) {
            names.push("can_quorum");
        }
        if self.has(Self::CAN_SALTED_DERIVATION) {
            names.push("can_salted_derivation");
        }
        if self.has(Self::HAS_DEVICE_STORAGE) {
            names.push("has_device_storage");
        }
        if self.has(Self::CAN_UPGRADE) {
            names.push("can_upgrade");
        }
        if self.has(Self::HAS_BIOMETRIC_EVIDENCE) {
            names.push("has_biometric_evidence");
        }
        names.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for ProviderCapabilities {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let names: Vec<String> = Vec::deserialize(deserializer)?;
        let mut caps = Self::BASE;
        for name in &names {
            match name.as_str() {
                "can_attest" => caps = caps.union(Self::CAN_ATTEST),
                "can_rewrap" => caps = caps.union(Self::CAN_REWRAP),
                "can_passphrase" => caps = caps.union(Self::CAN_PASSPHRASE),
                "can_quorum" => caps = caps.union(Self::CAN_QUORUM),
                "can_salted_derivation" => caps = caps.union(Self::CAN_SALTED_DERIVATION),
                "has_device_storage" => caps = caps.union(Self::HAS_DEVICE_STORAGE),
                "can_upgrade" => caps = caps.union(Self::CAN_UPGRADE),
                "has_biometric_evidence" => caps = caps.union(Self::HAS_BIOMETRIC_EVIDENCE),
                _ => {} // Ignore unknown capabilities (forward compat)
            }
        }
        Ok(caps)
    }
}

/// The core trait every sovereignty provider must implement.
///
/// The Genesis secret is always a 32-byte Ed25519 seed generated by ZeroPoint.
/// The provider controls how it's stored, how it's unlocked, and what physical
/// proof of presence is required.
pub trait SovereigntyProvider: Send + Sync {
    /// Which sovereignty mode this provider handles.
    fn mode(&self) -> SovereigntyMode;

    /// Detect whether this provider's hardware/software is available.
    fn detect(&self) -> ProviderCapability;

    /// Store the Genesis secret with this provider's gating mechanism.
    ///
    /// For biometrics: stores in OS credential store with biometric access control.
    /// For hardware wallets: encrypts the secret to a device-derived wrapping key.
    /// For login password: stores in OS credential store with default access.
    /// For file-based: writes to disk.
    fn save_secret(&self, secret: &[u8; 32]) -> Result<(), KeyError>;

    /// Load the Genesis secret, requiring the provider's proof of presence.
    ///
    /// For biometrics: triggers biometric scan before unlocking.
    /// For hardware wallets: requires device to be plugged in and confirmed.
    /// For login password: OS may prompt for login password.
    /// For file-based: reads from disk (no verification).
    fn load_secret(&self) -> Result<[u8; 32], KeyError>;

    /// Verify physical presence without loading the secret.
    ///
    /// Used for ongoing operations where the secret is already cached
    /// but we want to re-confirm the operator is present.
    fn verify_presence(&self) -> Result<(), KeyError>;

    /// Perform enrollment if this provider requires it.
    ///
    /// For face enrollment: captures webcam frames, builds template.
    /// For hardware wallets: pairs with device, derives wrapping key.
    /// For biometrics/password: may be a no-op (OS handles enrollment).
    fn enroll(&self) -> Result<Option<EnrollmentResult>, KeyError> {
        Ok(None) // Default: no enrollment needed
    }

    /// Advertise this provider's capabilities beyond the base trait.
    ///
    /// The ceremony, governance proxy, and UI use this to decide what
    /// operations to offer (rotation, quorum enrollment, etc.) without
    /// probing for errors or checking feature flags externally.
    fn capabilities(&self) -> ProviderCapabilities {
        ProviderCapabilities::BASE // Default: base operations only
    }

    /// Collect biometric evidence for the genesis transcript (v0.2).
    ///
    /// Returns cryptographic proof that a biometric verification occurred:
    /// a nonce-challenge-response binding the verification to a specific
    /// point in time, preventing replay.
    ///
    /// Only biometric providers return evidence. Hardware wallets and
    /// software gates return None.
    fn biometric_evidence(&self) -> Option<touchid::BiometricEvidence> {
        None // Default: no biometric evidence
    }

    /// Upgrade: re-gate an existing Genesis secret under this provider.
    ///
    /// This enables post-genesis sovereignty upgrades:
    ///   login_password → touch_id
    ///   touch_id → face_enroll (add secondary biometric)
    ///   login_password → yubikey
    ///
    /// The caller loads the secret from the OLD provider and passes it
    /// here. This provider enrolls (if needed) and saves the secret
    /// under its own gating mechanism. The old provider's entry is NOT
    /// deleted — that's the caller's responsibility after confirming
    /// the new entry works.
    ///
    /// Returns the enrollment result (if any) for transcript recording.
    fn upgrade_from(&self, secret: &[u8; 32]) -> Result<Option<EnrollmentResult>, KeyError> {
        // Default: enroll + save. Providers can override for custom flows.
        if self.detect().requires_enrollment {
            self.enroll()?;
        }
        self.save_secret(secret)?;
        Ok(None)
    }

    /// Human-readable name for the provider.
    fn display_name(&self) -> &'static str {
        self.mode().display_name()
    }
}

// ---------------------------------------------------------------------------
// Provider registry — detect all available providers
// ---------------------------------------------------------------------------

/// Scan the system and return capabilities for all known sovereignty providers.
pub fn detect_all_providers() -> Vec<ProviderCapability> {
    vec![
        // Biometric providers
        touchid::TouchIdProvider.detect(),
        fingerprint::FingerprintProvider.detect(),
        face::FaceEnrollProvider.detect(),
        windows_hello::WindowsHelloProvider.detect(),
        // Hardware wallet providers
        hardware::yubikey::YubiKeyProvider.detect(),
        hardware::ledger::LedgerProvider.detect(),
        hardware::trezor::TrezorProvider.detect(),
        hardware::onlykey::OnlyKeyProvider.detect(),
        // Software providers (always available)
        login_password::LoginPasswordProvider.detect(),
        file_based::FileProvider.detect(),
    ]
}

/// Get the appropriate provider for a given sovereignty mode.
pub fn provider_for(mode: SovereigntyMode) -> Box<dyn SovereigntyProvider> {
    let mode = mode.resolve();
    match mode {
        SovereigntyMode::TouchId => Box::new(touchid::TouchIdProvider),
        SovereigntyMode::Fingerprint => Box::new(fingerprint::FingerprintProvider),
        SovereigntyMode::FaceEnroll => Box::new(face::FaceEnrollProvider),
        SovereigntyMode::WindowsHello => Box::new(windows_hello::WindowsHelloProvider),
        SovereigntyMode::YubiKey => Box::new(hardware::yubikey::YubiKeyProvider),
        SovereigntyMode::Ledger => Box::new(hardware::ledger::LedgerProvider),
        SovereigntyMode::Trezor => Box::new(hardware::trezor::TrezorProvider),
        SovereigntyMode::OnlyKey => Box::new(hardware::onlykey::OnlyKeyProvider),
        SovereigntyMode::LoginPassword => Box::new(login_password::LoginPasswordProvider),
        SovereigntyMode::FileBased => Box::new(file_based::FileProvider),
        SovereigntyMode::LegacyBiometric => {
            // Should have been resolved above, but handle gracefully
            Box::new(login_password::LoginPasswordProvider)
        }
    }
}

// ---------------------------------------------------------------------------
// Singular sovereign root — canonical Genesis loader
// ---------------------------------------------------------------------------

/// Load the Genesis secret for this process.
///
/// On first call, tries the standard OS Keychain fast path (works for Touch
/// ID, login-password, and file-based modes that write the standard Keychain
/// during enrollment). If that misses — which only happens for hardware
/// wallets that hold the secret inside the device — reads `genesis.json` at
/// `genesis_record_path` to determine the sovereignty mode and invokes the
/// provider.
///
/// The result is cached in a process-scoped [`std::sync::OnceLock`]. Every
/// call after the first returns the cached secret without any Keychain or
/// provider access. This is the one-ceremony-per-process-lifetime guarantee.
///
/// Returns a `&'static` reference into the cache. The secret lives for the
/// process lifetime; `mlockall()` (applied in main where desired) prevents
/// swap exposure.
///
/// # Errors
///
/// On first failure the original error is returned. On subsequent calls when
/// the failure is cached, an actionable "re-run to retry" message is returned
/// instead of the raw provider error.
pub fn load_sovereign_root(
    genesis_record_path: &std::path::Path,
) -> Result<&'static [u8; 32], KeyError> {
    use std::sync::OnceLock;
    static CACHED: OnceLock<Result<[u8; 32], String>> = OnceLock::new();

    let already_cached = CACHED.get().is_some();
    let result = CACHED.get_or_init(|| {
        load_sovereign_root_uncached(genesis_record_path).map_err(|e| format!("{}", e))
    });
    match result {
        Ok(s) => Ok(s),
        Err(msg) => {
            if already_cached {
                Err(KeyError::CredentialStore(
                    "Sovereignty authentication failed earlier in this process — \
                     re-run to retry."
                        .into(),
                ))
            } else {
                Err(KeyError::CredentialStore(msg.clone()))
            }
        }
    }
}

fn load_sovereign_root_uncached(
    genesis_record_path: &std::path::Path,
) -> Result<[u8; 32], KeyError> {
    // Delegates to `load_active_genesis_secret_dispatch` — the canonical
    // sovereignty-mode-aware loader. Preserves the outer process-scoped
    // OnceLock caching in `load_sovereign_root`; only the composition logic
    // changed. See VAULT-KEY-SOVEREIGNTY-COMPOSITION-2026-07.md for
    // motivation.
    load_active_genesis_secret_dispatch(genesis_record_path)
}

/// Canonical sovereignty-mode-aware Genesis loader.
///
/// The fix per `VAULT-KEY-SOVEREIGNTY-COMPOSITION-2026-07.md` §"Fix path".
/// Dispatches based on `sovereignty_mode` in `genesis.json` rather than
/// probing the OS credential store unconditionally first. Prevents the
/// stale-material fast-path bug empirically hit 2026-07-17 during a
/// Touch ID → Trezor sovereignty migration on APOLLO: the credential
/// store still held old-era Genesis, the fast-path returned it, downstream
/// decrypt failed against the current Trezor-encrypted operator blob.
///
/// This is the recommended non-cached entry point for callers that need
/// process-local dispatch without the shared OnceLock cache. Most callers
/// should use `load_sovereign_root` instead, which caches the result.
///
/// Dispatch rules:
/// - **Hardware wallet modes** (YubiKey, Ledger, Trezor, OnlyKey): route
///   directly to the provider. Never consult credential store — the
///   credential store cannot hold the Genesis for these modes, and any
///   value it does hold is stale-era material from a prior sovereignty.
/// - **Credential-store-based modes** (TouchId, Fingerprint, FaceEnroll,
///   WindowsHello, LoginPassword, FileBased, LegacyBiometric): try
///   credential store first (the fast path for these modes is semantically
///   correct), fall back to provider path if the store is empty.
/// - **Missing genesis.json**: try credential store as a defensive
///   fallback (bootstrap/rotation-in-progress edge case), then return an
///   error naming the missing record.
pub fn load_active_genesis_secret(
    genesis_record_path: &std::path::Path,
) -> Result<[u8; 32], KeyError> {
    load_active_genesis_secret_dispatch(genesis_record_path)
}

/// Pure dispatch — reads sovereignty_mode from genesis.json and picks the
/// correct provider path. Extracted for testability.
fn load_active_genesis_secret_dispatch(
    genesis_record_path: &std::path::Path,
) -> Result<[u8; 32], KeyError> {
    // Read sovereignty_mode from genesis.json to select the dispatch strategy.
    // If genesis.json is missing (bootstrap or partial rotation), fall through
    // to the legacy credential-store-first behaviour so we don't regress
    // pre-sovereignty-refactor installs.
    let mode = read_sovereignty_mode(genesis_record_path);

    match mode {
        Some(m) if m.category() == SovereigntyCategory::HardwareWallet => {
            // Hardware wallet: skip credential store entirely. The store may
            // hold stale material from a prior sovereignty mode, and returning
            // it would produce silent-decrypt-failure downstream.
            let provider = provider_for_genesis_record(genesis_record_path)?;
            provider.load_secret()
        }
        Some(_) => {
            // Credential-store-based mode (TouchId, LoginPassword, etc.):
            // try credential store first, fall back to provider path if the
            // store is empty. This preserves the fast path for the modes
            // where it is semantically correct.
            if let Ok(secret) = crate::keyring::load_genesis_from_credential_store() {
                return Ok(secret);
            }
            let provider = provider_for_genesis_record(genesis_record_path)?;
            provider.load_secret()
        }
        None => {
            // No sovereignty_mode declared — legacy install or rotation in
            // progress. Try credential store as defensive fallback; if that
            // fails, surface a clear error.
            if let Ok(secret) = crate::keyring::load_genesis_from_credential_store() {
                return Ok(secret);
            }
            Err(KeyError::InvalidKeyMaterial(
                "genesis.json is missing or has no sovereignty_mode; \
                 credential store is also empty. Run `zp init` to establish \
                 Genesis under a sovereignty provider."
                    .into(),
            ))
        }
    }
}

/// Best-effort read of sovereignty_mode from genesis.json.
/// Returns `None` if the file is missing, unreadable, or has no mode field.
/// Callers must handle None as "legacy install" — not an error.
fn read_sovereignty_mode(
    genesis_record_path: &std::path::Path,
) -> Option<SovereigntyMode> {
    if !genesis_record_path.exists() {
        return None;
    }
    let raw = std::fs::read_to_string(genesis_record_path).ok()?;
    let record: serde_json::Value = serde_json::from_str(&raw).ok()?;
    let mode_str = record.get("sovereignty_mode")?.as_str()?;
    Some(SovereigntyMode::from_onboard_str(mode_str).resolve())
}

/// Read `genesis.json` and return the appropriate sovereignty provider.
///
/// Used by [`load_sovereign_root`] for hardware-wallet modes where the
/// standard Keychain fast path doesn't apply. Can also be called directly
/// by server-side code that needs to invoke the provider for a specific
/// record path.
pub fn provider_for_genesis_record(
    genesis_record_path: &std::path::Path,
) -> Result<Box<dyn SovereigntyProvider>, KeyError> {
    if !genesis_record_path.exists() {
        return Err(KeyError::InvalidKeyMaterial(
            "genesis.json not found — run `zp init` first".into(),
        ));
    }
    let raw = std::fs::read_to_string(genesis_record_path).map_err(|e| {
        KeyError::InvalidKeyMaterial(format!("failed to read genesis.json: {}", e))
    })?;
    let record: serde_json::Value = serde_json::from_str(&raw).map_err(|e| {
        KeyError::InvalidKeyMaterial(format!("failed to parse genesis.json: {}", e))
    })?;
    let mode_str = record
        .get("sovereignty_mode")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            KeyError::InvalidKeyMaterial("genesis.json missing sovereignty_mode".into())
        })?;
    let mode = SovereigntyMode::from_onboard_str(mode_str).resolve();
    Ok(provider_for(mode))
}

// ---------------------------------------------------------------------------
// Parsing from onboarding strings
// ---------------------------------------------------------------------------

impl SovereigntyMode {
    /// Parse from the string the onboarding UI sends.
    /// Handles both new specific modes and legacy strings.
    pub fn from_onboard_str(s: &str) -> Self {
        match s {
            "touch_id" | "touchid" | "touch-id" => SovereigntyMode::TouchId,
            "fingerprint" | "fprintd" => SovereigntyMode::Fingerprint,
            "face_enroll" | "face-enroll" | "face" | "camera" => SovereigntyMode::FaceEnroll,
            "windows_hello" | "windows-hello" | "windowshello" | "hello" => {
                SovereigntyMode::WindowsHello
            }
            "yubikey" | "yubi_key" | "yubi-key" => SovereigntyMode::YubiKey,
            "ledger" => SovereigntyMode::Ledger,
            "trezor" => SovereigntyMode::Trezor,
            "onlykey" | "only_key" | "only-key" => SovereigntyMode::OnlyKey,
            "login-password" | "login_password" | "login" | "password" => {
                SovereigntyMode::LoginPassword
            }
            "file-based" | "file_based" | "file" => SovereigntyMode::FileBased,
            // Legacy: "biometric" or "bio" resolves at runtime
            "biometric" | "bio" => SovereigntyMode::LegacyBiometric,
            // Auto-detect: pick the best available
            _ => SovereigntyMode::LoginPassword,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sovereignty_mode_display() {
        assert_eq!(SovereigntyMode::TouchId.to_string(), "touch_id");
        assert_eq!(SovereigntyMode::YubiKey.to_string(), "yubi_key");
        assert_eq!(SovereigntyMode::LoginPassword.to_string(), "login_password");
        assert_eq!(SovereigntyMode::FileBased.to_string(), "file_based");
    }

    #[test]
    fn test_sovereignty_mode_serde_roundtrip() {
        let mode = SovereigntyMode::TouchId;
        let json = serde_json::to_string(&mode).unwrap();
        assert_eq!(json, "\"touch_id\"");
        let parsed: SovereigntyMode = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, mode);
    }

    #[test]
    fn test_legacy_biometric_deserializes() {
        let parsed: SovereigntyMode = serde_json::from_str("\"biometric\"").unwrap();
        assert_eq!(parsed, SovereigntyMode::LegacyBiometric);
    }

    #[test]
    fn test_from_onboard_str() {
        assert_eq!(
            SovereigntyMode::from_onboard_str("touch-id"),
            SovereigntyMode::TouchId
        );
        assert_eq!(
            SovereigntyMode::from_onboard_str("yubikey"),
            SovereigntyMode::YubiKey
        );
        assert_eq!(
            SovereigntyMode::from_onboard_str("biometric"),
            SovereigntyMode::LegacyBiometric
        );
    }

    #[test]
    fn test_detect_all_providers_does_not_panic() {
        let caps = detect_all_providers();
        assert!(caps.len() >= 2); // At least login_password + file_based
    }

    // ── v0.2 biometric tests ─────────────────────────────────────

    #[test]
    fn test_biometric_evidence_structure() {
        let evidence = BiometricEvidence {
            method: "touchid".into(),
            verified_at: "2026-04-17T12:00:00Z".into(),
            challenge_nonce: "aa".repeat(32),
            challenge_response: "bb".repeat(32),
            os_enforced: true,
            hardware_attestation: String::new(),
        };

        let json = serde_json::to_value(&evidence).unwrap();
        assert_eq!(json["method"], "touchid");
        assert_eq!(json["os_enforced"], true);
        assert!(json["challenge_nonce"].as_str().unwrap().len() == 64);
        assert!(json["challenge_response"].as_str().unwrap().len() == 64);
    }

    #[test]
    fn test_biometric_evidence_in_transcript_json() {
        // Verify that biometric evidence serializes correctly for inclusion
        // in genesis transcripts
        let evidence = BiometricEvidence {
            method: "faceid".into(),
            verified_at: chrono::Utc::now().to_rfc3339(),
            challenge_nonce: hex::encode([0xaa; 32]),
            challenge_response: hex::encode([0xbb; 32]),
            os_enforced: false,
            hardware_attestation: String::new(),
        };

        let transcript = serde_json::json!({
            "ceremony": "genesis",
            "biometric_evidence": evidence,
        });

        let evidence_obj = &transcript["biometric_evidence"];
        assert_eq!(evidence_obj["method"], "faceid");
        assert_eq!(evidence_obj["os_enforced"], false);
    }

    #[test]
    fn test_provider_capabilities_upgrade_flag() {
        let caps = ProviderCapabilities::BASE
            .union(ProviderCapabilities::CAN_UPGRADE)
            .union(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE);

        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
        assert!(!caps.has(ProviderCapabilities::CAN_ATTEST));
    }

    #[test]
    fn test_provider_capabilities_serde_roundtrip() {
        let caps = ProviderCapabilities::CAN_UPGRADE
            .union(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE);

        let json = serde_json::to_string(&caps).unwrap();
        assert!(json.contains("can_upgrade"));
        assert!(json.contains("has_biometric_evidence"));

        let parsed: ProviderCapabilities = serde_json::from_str(&json).unwrap();
        assert!(parsed.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(parsed.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_touchid_provider_has_upgrade_capability() {
        let provider = touchid::TouchIdProvider;
        let caps = provider.capabilities();
        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_face_provider_has_upgrade_capability() {
        let provider = face::FaceEnrollProvider;
        let caps = provider.capabilities();
        assert!(caps.has(ProviderCapabilities::CAN_UPGRADE));
    }

    #[test]
    fn test_login_password_default_capabilities() {
        let provider = login_password::LoginPasswordProvider;
        let caps = provider.capabilities();
        // Login password has no special capabilities
        assert!(!caps.has(ProviderCapabilities::CAN_UPGRADE));
        assert!(!caps.has(ProviderCapabilities::HAS_BIOMETRIC_EVIDENCE));
    }

    #[test]
    fn test_sovereignty_upgrade_same_mode_noop() {
        // Upgrading to the same mode should be detected by the handler
        // (not tested here — that's a server-layer test)
        // But we verify the provider trait has upgrade_from
        let provider = touchid::TouchIdProvider;
        assert_eq!(provider.mode(), SovereigntyMode::TouchId);
    }

    // ── singular_sovereign_root discipline-pin tests ─────────────────

    #[test]
    fn provider_for_genesis_record_parses_known_modes() {
        let dir = tempfile::tempdir().unwrap();
        let genesis_path = dir.path().join("genesis.json");

        let cases: &[(&str, SovereigntyMode)] = &[
            ("touch_id", SovereigntyMode::TouchId),
            ("touchid", SovereigntyMode::TouchId),
            ("login-password", SovereigntyMode::LoginPassword),
            ("login_password", SovereigntyMode::LoginPassword),
            ("file-based", SovereigntyMode::FileBased),
            ("file_based", SovereigntyMode::FileBased),
            ("trezor", SovereigntyMode::Trezor),
            ("fingerprint", SovereigntyMode::Fingerprint),
        ];

        for &(mode_str, expected) in cases {
            let json = format!(r#"{{"sovereignty_mode": "{}"}}"#, mode_str);
            std::fs::write(&genesis_path, &json).unwrap();

            let provider =
                provider_for_genesis_record(&genesis_path).unwrap_or_else(|e| {
                    panic!("provider_for_genesis_record failed for '{}': {}", mode_str, e)
                });
            assert_eq!(
                provider.mode(),
                expected,
                "wrong provider for mode_str='{}'",
                mode_str
            );
        }
    }

    #[test]
    fn provider_for_genesis_record_errors_on_missing_file() {
        let dir = tempfile::tempdir().unwrap();
        let genesis_path = dir.path().join("genesis.json");
        // genesis.json intentionally absent
        let err = provider_for_genesis_record(&genesis_path)
            .err()
            .expect("expected Err when genesis.json is missing");
        let msg = format!("{}", err);
        assert!(
            msg.contains("genesis.json not found"),
            "expected 'genesis.json not found' in error, got: {}",
            msg
        );
    }

    #[test]
    fn provider_for_genesis_record_errors_on_missing_mode_field() {
        let dir = tempfile::tempdir().unwrap();
        let genesis_path = dir.path().join("genesis.json");
        std::fs::write(&genesis_path, r#"{"other_field": "value"}"#).unwrap();

        let err = provider_for_genesis_record(&genesis_path)
            .err()
            .expect("expected Err when sovereignty_mode field is absent");
        let msg = format!("{}", err);
        assert!(
            msg.contains("sovereignty_mode"),
            "expected 'sovereignty_mode' in error, got: {}",
            msg
        );
    }

    #[test]
    fn provider_for_genesis_record_errors_on_invalid_json() {
        let dir = tempfile::tempdir().unwrap();
        let genesis_path = dir.path().join("genesis.json");
        std::fs::write(&genesis_path, "not valid json {{{").unwrap();

        let result = provider_for_genesis_record(&genesis_path);
        assert!(result.is_err(), "expected error on malformed JSON");
    }

    #[test]
    fn load_sovereign_root_errors_clearly_on_missing_genesis() {
        // When genesis.json doesn't exist the fast path (Keychain) may also
        // fail (no item in test namespace), but the provider path gives a
        // clearer error. This test verifies the error message is actionable.
        let dir = tempfile::tempdir().unwrap();
        let genesis_path = dir.path().join("genesis.json");
        // Do NOT write genesis.json
        let result = load_sovereign_root(&genesis_path);
        // Either the Keychain fast path failed or the provider path failed;
        // either way, the call must not panic and must return an error.
        assert!(
            result.is_err(),
            "expected error when genesis.json is absent and Keychain is empty"
        );
    }

    // ── Regression tests for eb1975f path-derivation bug ────────────

    /// Regression test: the old load_sovereign_root_uncached fast path called
    /// Keyring::open(genesis_record_path.parent().join("keys")). When
    /// genesis_record_path = .../keys/genesis.json (the Keyring path shape),
    /// parent() = .../keys and join("keys") = .../keys/keys — a directory
    /// that didn't exist and was silently created as a side effect.
    ///
    /// After the fix, the fast path calls load_genesis_from_credential_store()
    /// directly with no path derivation and no Keyring::open() side effects.
    #[test]
    fn load_sovereign_root_uncached_creates_no_side_effect_directories() {
        let _guard = crate::test_sync::serial_guard();
        let dir = tempfile::tempdir().unwrap();

        // Simulate the keyring path shape: genesis.json inside a keys/ dir.
        let keys_dir = dir.path().join("keys");
        std::fs::create_dir_all(&keys_dir).unwrap();
        let genesis_path = keys_dir.join("genesis.json");

        // Write a valid genesis.json so the provider path can parse the mode.
        let genesis_json = serde_json::json!({"sovereignty_mode": "login-password"});
        std::fs::write(&genesis_path, genesis_json.to_string()).unwrap();

        // Call the uncached loader. Both paths may fail in the test namespace
        // (no credential store item) — that's fine. What matters is that no
        // unexpected directories were created.
        let _ = load_sovereign_root_uncached(&genesis_path);

        // The buggy code created keys/keys. After the fix this must not exist.
        let unexpected = dir.path().join("keys").join("keys");
        assert!(
            !unexpected.exists(),
            "load_sovereign_root_uncached must not create a keys/keys directory \
             (this was the path-derivation bug from eb1975f); found: {:?}",
            unexpected
        );
    }

    /// Verify that load_sovereign_root_uncached's fast path uses
    /// load_genesis_from_credential_store() directly: when the credential
    /// store returns a secret, the function returns it without touching
    /// genesis.json for the fast path.
    ///
    /// We verify this indirectly: if the fast path calls
    /// load_genesis_from_credential_store() and gets a non-empty result,
    /// it returns immediately — the provider path (which reads genesis.json)
    /// is only reached on failure. In test mode, the credential store is
    /// uncached, so we can observe the exact call path.
    #[test]
    fn load_sovereign_root_uncached_fast_path_is_credential_store_not_path_derivation() {
        let _guard = crate::test_sync::serial_guard();
        let dir = tempfile::tempdir().unwrap();

        // genesis.json exists with a real mode so the provider path works if reached.
        let genesis_path = dir.path().join("genesis.json");
        let genesis_json = serde_json::json!({"sovereignty_mode": "login-password"});
        std::fs::write(&genesis_path, genesis_json.to_string()).unwrap();

        // Call with a path whose parent().join("keys") does NOT match where
        // the genesis.json actually lives. Under the old (buggy) fast path,
        // this would try to open a keyring at the wrong location and fail.
        // Under the new fast path, the location of genesis.json is irrelevant
        // to the credential-store lookup.
        //
        // In the test namespace, load_genesis_from_credential_store() will
        // fail (no item exists). We just assert the function returns an error
        // without creating unexpected directories — that's sufficient to
        // distinguish the new path from the old one.
        let result = load_sovereign_root_uncached(&genesis_path);

        // Either path (fast or provider) may fail in the test environment.
        // The regression was a panic or unexpected directory, not an error.
        // A clean Err is the correct observable outcome here.
        match result {
            Ok(_) | Err(_) => {} // both are acceptable in test environment
        }

        // Regardless, no unexpected directory relative to genesis_path was
        // created. The old code would have called Keyring::open(dir.path().join("keys"))
        // for this path shape.
        let unexpected = dir.path().join("keys");
        // The "keys" subdir should only exist if we explicitly created it.
        assert!(
            !unexpected.exists(),
            "fast path must not create side-effect directories; found: {:?}",
            unexpected
        );
    }

    /// Verify Keyring::genesis_secret() returns the same secret as the
    /// credential store when genesis.json is present. This is the new
    /// public method used by CLI callers after the eb1975f regression fix.
    #[test]
    fn keyring_genesis_secret_errors_without_genesis_json() {
        let _guard = crate::test_sync::serial_guard();
        let dir = tempfile::tempdir().unwrap();
        let keyring = crate::keyring::Keyring::open(dir.path()).unwrap();

        // No genesis.json written — should fail with a clear message.
        let result = keyring.genesis_secret();
        assert!(result.is_err(), "genesis_secret() must fail without genesis.json");
        let msg = format!("{}", result.unwrap_err());
        assert!(
            msg.contains("genesis.json not found") || msg.contains("No genesis.json"),
            "expected actionable error, got: {}",
            msg
        );
    }

    // ── load_active_genesis_secret dispatch (VAULT-KEY-SOVEREIGNTY-COMPOSITION) ──

    /// Helper: write a minimal genesis.json declaring the given sovereignty mode.
    /// The other fields are placeholders — only sovereignty_mode is read by
    /// read_sovereignty_mode.
    fn write_genesis_json(dir: &std::path::Path, mode_str: &str) -> std::path::PathBuf {
        let path = dir.join("genesis.json");
        let content = serde_json::json!({
            "algorithm": "Ed25519",
            "genesis_public_key": "0000000000000000000000000000000000000000000000000000000000000000",
            "operator": "testop",
            "operator_public_key": "1111111111111111111111111111111111111111111111111111111111111111",
            "sovereignty_mode": mode_str,
            "timestamp": "2026-07-21T00:00:00+00:00",
            "version": "2.0"
        });
        std::fs::write(&path, serde_json::to_string_pretty(&content).unwrap()).unwrap();
        path
    }

    #[test]
    fn read_sovereignty_mode_returns_none_when_file_missing() {
        let dir = tempfile::tempdir().unwrap();
        let missing = dir.path().join("does-not-exist.json");
        assert!(super::read_sovereignty_mode(&missing).is_none());
    }

    #[test]
    fn read_sovereignty_mode_returns_mode_for_trezor() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_genesis_json(dir.path(), "trezor");
        let mode = super::read_sovereignty_mode(&path).expect("mode present");
        assert_eq!(mode, SovereigntyMode::Trezor);
    }

    #[test]
    fn read_sovereignty_mode_returns_mode_for_touch_id() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_genesis_json(dir.path(), "touch_id");
        let mode = super::read_sovereignty_mode(&path).expect("mode present");
        assert_eq!(mode, SovereigntyMode::TouchId);
    }

    #[test]
    fn read_sovereignty_mode_resolves_legacy_biometric() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_genesis_json(dir.path(), "biometric");
        let mode = super::read_sovereignty_mode(&path).expect("mode present");
        // resolve() converts LegacyBiometric to platform-native concrete mode
        assert_ne!(mode, SovereigntyMode::LegacyBiometric);
    }

    #[test]
    fn read_sovereignty_mode_returns_none_when_field_absent() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("genesis.json");
        std::fs::write(&path, r#"{"version":"2.0"}"#).unwrap();
        assert!(super::read_sovereignty_mode(&path).is_none());
    }

    /// Hardware wallet modes must be classified as HardwareWallet category.
    /// The dispatch logic in load_active_genesis_secret_dispatch relies on this
    /// classification to decide whether to skip the credential store fast path.
    #[test]
    fn hardware_wallet_modes_are_categorized_correctly() {
        assert_eq!(
            SovereigntyMode::Trezor.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_eq!(
            SovereigntyMode::YubiKey.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_eq!(
            SovereigntyMode::Ledger.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_eq!(
            SovereigntyMode::OnlyKey.category(),
            SovereigntyCategory::HardwareWallet
        );
    }

    /// Credential-store-based modes must NOT be classified as HardwareWallet.
    /// The dispatch preserves the credential store fast path for these modes.
    #[test]
    fn credential_store_modes_are_not_hardware_wallet() {
        assert_ne!(
            SovereigntyMode::TouchId.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_ne!(
            SovereigntyMode::LoginPassword.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_ne!(
            SovereigntyMode::FileBased.category(),
            SovereigntyCategory::HardwareWallet
        );
        assert_ne!(
            SovereigntyMode::Fingerprint.category(),
            SovereigntyCategory::HardwareWallet
        );
    }

    /// Regression test for the bug empirically hit 2026-07-17: with a Trezor
    /// sovereignty declared in genesis.json AND stale material in the OS
    /// credential store, the pre-fix code returned the stale material.
    /// Post-fix, hardware-wallet mode must route straight to the provider
    /// (which will error without a real Trezor, but the error class must be
    /// provider-related, not "returned stale credential store material").
    ///
    /// We can't test the "provider returns" case without a real Trezor, but
    /// we CAN test that the dispatch does not silently succeed via the
    /// credential store fast path when hardware wallet mode is declared.
    /// This test verifies: with hardware wallet mode declared, the dispatch
    /// does not use the credential-store fast-path result.
    #[test]
    fn hardware_wallet_dispatch_does_not_return_credential_store_fast_path() {
        let dir = tempfile::tempdir().unwrap();
        let path = write_genesis_json(dir.path(), "trezor");
        let mode = super::read_sovereignty_mode(&path).expect("mode present");
        // Category check ensures the dispatch WILL take the hardware wallet
        // branch. The actual load_active_genesis_secret_dispatch call would
        // require a real Trezor to succeed; the test verifies the
        // classification that gates the branch.
        assert_eq!(mode.category(), SovereigntyCategory::HardwareWallet);
        // Verify the hardware-wallet branch would run:
        //   - It would NOT consult credential store (that path is skipped
        //     entirely when category == HardwareWallet).
        //   - It WOULD invoke provider_for_genesis_record — which requires
        //     a real Trezor for successful completion.
    }

    /// Dispatch when no sovereignty_mode is declared and credential store is
    /// unavailable returns a clear error naming both surfaces.
    #[test]
    fn dispatch_with_no_mode_and_no_credential_store_returns_actionable_error() {
        let _guard = crate::test_sync::serial_guard();
        let dir = tempfile::tempdir().unwrap();
        // No genesis.json written and (assuming) no test-scoped credential
        // store material. Dispatch should return an error mentioning the
        // remediation path.
        let missing_genesis = dir.path().join("genesis.json");
        let result = super::load_active_genesis_secret_dispatch(&missing_genesis);
        // The result should be Err — either because credential store is
        // empty in the test env, or because the fallback error fires. Both
        // are acceptable; the invariant is that we don't panic.
        if let Err(e) = result {
            let msg = format!("{}", e);
            // On CI or dev machines without credential store material for
            // the test service, the error should mention `zp init` or
            // sovereignty provider. We don't require exact text — different
            // credential store backends produce different error text —
            // just that the error IS surfaced (not swallowed).
            assert!(!msg.is_empty(), "error message must not be empty");
        }
        // If the test environment DOES have credential store material (e.g.,
        // running on a dev machine where Ken did a prior init), the fallback
        // WOULD succeed — that's also acceptable behaviour per the dispatch's
        // legacy-install fallback branch.
    }
}
